Repository maxi-blocks/maxi-blocks, pull requests merged in 2023-11, with the labels that each got.

#5221 Fix shape divider
  src/blocks/container-maxi/save.js
Labels: 😁 final code testing, 👀 *****fast track***** 👀

#5229 Fix global padding for full-width containers
  core/class-maxi-styles.php
  e2e-tests/blocks/text-maxi/list.spec.js
  src/blocks/container-maxi/style.scss
Labels: 😁 final code testing

#5219 Issue 5084 - rendering DC at a new site
  src/extensions/DC/utils.js
  src/extensions/DC/validateDCAttributes.js
  src/extensions/DC/withMaxiContextLoop.js
  src/extensions/DC/withMaxiDC.js
Labels: 😁 final code testing

#5240 Fix hover from SC on backend
  src/extensions/style-cards/getSCStyles.js
  src/extensions/style-cards/test/__snapshots__/getSCStyles.js.snap
Labels: 🙏 high priority, 😁 final code testing, ⛏ ++ needs deep testing ++ ⛏, 👀 *****fast track***** 👀, 🌈🌈 next major update 🌈🌈

#5244 Next update - version 1.5.3
  changelog.txt
  e2e-tests/blocks/Divider-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/Group-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/button-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/column-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/container-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/number-counter-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/row-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/svg-icon-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/text-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/video-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/components/background/__snapshots__/SVGIconBackground.spec.js.snap
  e2e-tests/components/icon-control/__snapshots__/index.spec.js.snap
  e2e-tests/components/repeater/__snapshots__/index.spec.js.snap
  e2e-tests/components/repeater/content.js
  e2e-tests/components/svg-color/__snapshots__/index.spec.js.snap
  e2e-tests/components/svg-stroke-width-control/__snapshots__/index.spec.js.snap
  e2e-tests/components/video-options-control/__snapshots__/index.spec.js.snap
  plugin.php
  readme.txt
  src/editor/auth/index.js
  src/editor/library/container.js
  src/editor/library/modal.js
  src/editor/library/toolbar.js
Labels: 😁 final code testing, 👀 *****fast track***** 👀

#5254 Faster list editing on wp 6.4+
  src/blocks/text-maxi/edit.js
  src/components/toolbar/components/text-list-options/index.js
  src/components/toolbar/index.js
Labels: 🙏 high priority, 😁 final code testing, 👀 *****fast track***** 👀, lgtm, size:L

#5271 Issue 5226 - Shape mask remove icon
  src/editor/library/editor.scss
Labels: 😁 final code testing, lgtm, size:XS

#5272 Issue 5226 - Baby toolbar padding extra reset icon
  src/components/axis-control/index.js
Labels: 😁 final code testing, lgtm, size:XS

#5258 Issue 5255 - Toolbar bugs
  src/components/box-shadow-control/index.js
  src/components/toolbar/components/text-margin/editor.scss
Labels: 😁 final code testing, lgtm, size:S

#5263 Issue 5259: CL
  core/class-maxi-styles.php
  src/blocks/accordion-maxi/block.json
  src/blocks/column-maxi/block.json
  src/blocks/column-maxi/inspector.js
  src/blocks/container-maxi/block.json
  src/blocks/container-maxi/inspector.js
  src/blocks/group-maxi/block.json
  src/blocks/pane-maxi/block.json
  src/blocks/row-maxi/block.json
  src/blocks/slide-maxi/block.json
  src/blocks/slider-maxi/block.json
  src/components/context-loop/index.js
  src/extensions/DC/constants.js
  src/extensions/DC/withMaxiContextLoop.js
  src/extensions/copy-paste/excludeAttributes.js
  src/extensions/styles/defaults/contextLoop.js
Labels: 🙏 high priority, ⛏ ++ needs deep testing ++ ⛏, lgtm, size:XXL

#5279 Fix on click styles for IB on frontend
  e2e-tests/components/toolbar/components/icon-background/index.spec.js
  js/maxi-relations.js
Labels: 😁 final code testing, size:S

#5278 Fix typography values for text in IB
  core/admin/class-maxi-dashboard.php
  e2e-tests/components/relation-control/button-maxi.spec.js
  src/components/relation-control/index.js
Labels: 😁 final code testing, size:S

#5243 Issue 5022 - Canvas hover toggle for Icon, Transform, CustomCSS
  core/blocks/utils/default-group-attributes.json
  e2e-tests/blocks/button-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/svg-icon-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/video-maxi/__snapshots__/index.spec.js.snap
  src/blocks/accordion-maxi/block.json
  src/blocks/button-maxi/block.json
  src/blocks/button-maxi/data.js
  src/blocks/divider-maxi/block.json
  src/blocks/image-maxi/block.json
  src/blocks/map-maxi/block.json
  src/blocks/number-counter-maxi/block.json
  src/blocks/search-maxi/block.json
  src/blocks/slider-maxi/block.json
  src/blocks/slider-maxi/styles.js
  src/blocks/svg-icon-maxi/block.json
  src/blocks/svg-icon-maxi/styles.js
  src/blocks/text-maxi/block.json
  src/blocks/video-maxi/block.json
  src/blocks/video-maxi/data.js
  src/blocks/video-maxi/styles.js
  src/components/inspector-tabs/inspector-icon.js
  src/components/transform-control/index.js
  src/components/transform-control/rotate-control.js
  src/components/transform-control/utils.js
  src/extensions/styles/custom-css/constants.js
  src/extensions/styles/custom-css/createIconSelectors.js
  src/extensions/styles/custom-css/createSelectors.js
  src/extensions/styles/custom-css/getBaseSelectors.js
  src/extensions/styles/custom-css/getNormalAndHoverSelectors.js
  src/extensions/styles/custom-css/getPseudoElementSelectors.js
  src/extensions/styles/custom-css/index.js
  src/extensions/styles/custom-css/test/__snapshots__/createSelectors.js.snap
  src/extensions/styles/defaults/iconHover.js
  src/extensions/styles/helpers/getButtonIconStyles.js
  src/extensions/styles/helpers/getSVGStyles.js
  src/extensions/styles/helpers/getTransformStyles.js
  src/extensions/styles/helpers/test/__snapshots__/getSVGStyles.js.snap
  src/extensions/styles/migrators/test/__snapshots__/utils.js.snap
Labels: 😁 final code testing, lgtm, size:XXL, 1.5.6

#5274 Issue 4903 rel attribute
  e2e-tests/blocks/text-maxi/__snapshots__/index.spec.js.snap
  src/blocks/button-maxi/save.js
  src/components/toolbar/components/text-link/utils.js
  src/extensions/save/utils.js
Labels: front testing, lgtm, size:L, 1.5.6
