Repository maxi-blocks/maxi-blocks, pull requests merged in 2023-12, with the labels that each got.

#5296 Fix: Woo DC with removed products
  core/class-maxi-dynamic-content.php
  src/blocks/column-maxi/edit.js
Labels: 🙏 high priority, size:M, 1.5.6

#5273 Issue 5211 - Add interaction builder (IB) preview in editor
  src/components/relation-control/index.js
  src/extensions/attributes/getBlockNameFromUniqueID.js
  src/extensions/attributes/index.js
  src/extensions/maxi-block/maxiBlockComponent.js
  src/extensions/relations/Relation.js
  src/extensions/relations/getAdvancedSettings.js
  src/extensions/relations/processRelations.js
  src/extensions/styles/migrators/SVGTransitionMigrator.js
  src/extensions/styles/migrators/bottomGapMigrator.js
  src/extensions/styles/migrators/dcLinkBlocksMigrator.js
  src/extensions/styles/migrators/maxiAttributesMigrator.js
  src/extensions/styles/migrators/opacityTransitionMigrator.js
  src/extensions/styles/migrators/test/utils.js
  src/extensions/styles/migrators/transitionMigrator.js
  src/extensions/styles/migrators/uniqueIDMigrator.js
  src/extensions/styles/migrators/utils.js
Labels: 😁 final code testing, lgtm, size:XXL, 1.5.6

#5297 1.5.6
  changelog.txt
  e2e-tests/blocks/Divider-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/Group-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/button-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/column-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/container-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/number-counter-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/row-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/svg-icon-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/text-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/video-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/components/background/__snapshots__/SVGIconBackground.spec.js.snap
  e2e-tests/components/icon-control/__snapshots__/index.spec.js.snap
  e2e-tests/components/repeater/__snapshots__/index.spec.js.snap
  e2e-tests/components/repeater/content.js
  e2e-tests/components/svg-color/__snapshots__/index.spec.js.snap
  e2e-tests/components/svg-stroke-width-control/__snapshots__/index.spec.js.snap
  e2e-tests/components/video-options-control/__snapshots__/index.spec.js.snap
  plugin.php
  readme.txt
  src/blocks/map-maxi/block.json
  src/blocks/slider-maxi/block.json
Labels: size:M

#5292 Issue 5070 Dynamic Content character limit info
  src/components/advanced-number-control/index.js
  src/components/dynamic-content/custom-date-formatting/editor.scss
  src/components/dynamic-content/custom-date-formatting/index.js
  src/components/dynamic-content/index.js
  src/components/text-control/index.js
Labels: 😁 final code testing, lgtm, size:L

#5302 Column test - Container timeout error
  e2e-tests/blocks/column-maxi/index.spec.js
  e2e-tests/blocks/container-maxi/index.spec.js
  e2e-tests/blocks/row-maxi/index.spec.js
  e2e-tests/components/arrow-control/index.spec.js
  e2e-tests/components/arrow-displayer/index.spec.js
  e2e-tests/components/breadcrumbs/index.spec.js
  e2e-tests/components/column-pattern/index.spec.js
  e2e-tests/components/dropdown/index.spec.js
  e2e-tests/components/full-size-control/index.spec.js
  e2e-tests/components/indicators/index.spec.js
  e2e-tests/components/relation-control/column-maxi.spec.js
Labels: mvp legacy :hammer_and_wrench:, mvp fix :fast_forward:, lgtm, size:S

#5304 Issue 5301 image resize
  src/blocks/image-maxi/attributes.js
  src/blocks/image-maxi/block.json
  src/blocks/image-maxi/components/dimension-tab/index.js
  src/blocks/image-maxi/data.js
  src/blocks/image-maxi/edit.js
  src/blocks/image-maxi/inspector.js
  src/blocks/image-maxi/styles.js
  src/components/full-size-control/index.js
  src/components/maxi-popover-button/index.js
  src/extensions/copy-paste/test/__snapshots__/copy-paste.js.snap
  src/extensions/copy-paste/test/copy-paste.js
  src/extensions/styles/helpers/getImgWidthStyles.js
  src/extensions/styles/helpers/index.js
  src/extensions/styles/migrators/blockMigrator.js
  src/extensions/styles/migrators/imageResponsiveWidth.js
Labels: 😁 final code testing, mvp fix :fast_forward:, lgtm, size:L

#5315 Issue 5299 translations
  core/admin/class-maxi-dashboard.php
  languages/maxi-blocks.pot
  plugin.php
Labels: lgtm, size:L

#5309 Repeater: unique id
  src/extensions/maxi-block/withMaxiProps.js
  src/extensions/repeater/validateRowColumnsStructure.js
Labels: lgtm, size:XS

#5298 Issue 4874 - Image URL source for image,video-maxi & image layer
  e2e-tests/components/background/imageLayer.spec.js
  src/blocks/image-maxi/attributes.js
  src/blocks/image-maxi/edit.js
  src/blocks/video-maxi/edit.js
  src/components/background-control/imageLayer.js
  src/components/background-control/videoLayer.js
  src/components/image-url-upload/editor.scss
  src/components/image-url-upload/index.js
  src/components/index.js
  src/components/media-uploader-control/index.js
  src/components/svg-fill-control/index.js
  src/components/text-control/index.js
  src/components/text-input/index.js
  src/components/toolbar/components/media-upload/editor.scss
  src/components/toolbar/components/media-upload/index.js
  src/components/toolbar/editor.scss
  src/extensions/svg/injectImgSVG.js
Labels: 😁 final code testing, lgtm, size:XL, 1.5.7

#5305 Issue 5275 - RTL 01
  src/blocks/cloud-maxi/editor.scss
  src/editor/library/editor.scss
  src/editor/style-cards/editor.scss
Labels: 😁 final code testing, lgtm, size:L

#5293 Issue 4377 - Margin indicator overlapping
  e2e-tests/components/indicators/__snapshots__/index.spec.js.snap
  e2e-tests/components/toolbar/components/column-pattern/index.spec.js
  e2e-tests/components/toolbar/components/vertical-align/index.spec.js
  src/blocks/container-maxi/edit.js
  src/components/axis-control/index.js
  src/components/block-indicators/editor.scss
Labels: 😁 final code testing, lgtm, size:L

#5331 Issue 5319 & 5320 - WooCommerce relation by-category/tag backend fix
  src/extensions/DC/constants.js
  src/extensions/DC/getDCEntity.js
  src/extensions/DC/getWCContent.js
  src/extensions/DC/getWooCommerceData.js
  src/extensions/DC/utils.js
Labels: 😁 final code testing, lgtm, size:M

#5326 Issue 5180 - Fix DC link save on CL change
  src/extensions/DC/withMaxiDC.js
Labels: 😁 final code testing, lgtm, size:S

#5327 Issue 5317 - Fix DC link for SVG, Group, Columns
  src/components/link-control/index.js
  src/components/toolbar/components/link/index.js
  src/extensions/DC/getDCNewLinkSettings.js
  src/extensions/DC/index.js
  src/extensions/DC/useMaxiDCLink.js
  src/extensions/DC/withMaxiContextLoopContext.js
  src/extensions/DC/withMaxiDC.js
Labels: 😁 final code testing, lgtm, size:L, bug, code, enhancement

#5329 Fix clicks on blocks speed
  src/extensions/maxi-block/maxiBlockComponent.js
  src/extensions/maxi-block/propsObjectCleaner.js
  src/extensions/repeater/updateRelationsInColumn.js
  src/extensions/styles/getDefaultAttribute.js
  src/extensions/styles/getLastBreakpointAttribute.js
  src/extensions/styles/helpers/getSizeStyles.js
Labels: 😁 final code testing, lgtm, size:L

#5338 Issue 5203 - Hide Gutenberg's popover for Maxi blocks
  src/extensions/maxi-block/maxiBlockComponent.js
Labels: 😁 final code testing, lgtm, size:S

#5345 Issue 5342: UI changes
  core/admin/admin.scss
  core/admin/class-maxi-dashboard.php
  core/class-maxi-api.php
  package-lock.json
  package.json
  src/components/toolbar/components/help/index.js
  src/components/toolbar/index.js
  src/editor/crisp-chat/index.js
  src/editor/library/MasonryItem.js
  src/editor/library/toolbar.js
  src/editor/responsive-selector/index.js
Labels: 🙏 high priority, front testing, lgtm, size:L, 1.5.8

#5350 DC media when the image is missing
  src/extensions/DC/getDCMedia.js
Labels: 😁 final code testing, lgtm, size:M

#5339 Issue 5332 - Fix `image-maxi` hover effect frontend
  e2e-tests/components/textarea-control/__snapshots__/index.spec.js.snap
  src/blocks/image-maxi/components/hover-effect-control/constants.js
  src/blocks/image-maxi/components/hover-effect-control/index.js
  src/blocks/image-maxi/inspector.js
  src/blocks/image-maxi/styles.js
  src/components/hover-preview/index.js
  src/components/inspector-tabs/inspector-scroll-effects.js
  src/components/inspector-tabs/inspector-transform.js
  src/components/transform-control/index.js
  src/extensions/styles/defaults/hover.js
  src/extensions/styles/styleProcessor.js
  src/extensions/styles/utils.js
Labels: 😁 final code testing, lgtm, size:XXL, 1.5.9

#5334 Issue 5333 - Search button styles in toolbar
  src/components/link-control/editor.scss
Labels: front testing, lgtm, size:S

#5348 Issue 5280 - Replaced deprecated position prop with placement
  src/components/block-inserter/index.js
  src/components/button/index.js
  src/components/clip-path-control/doublePoint.js
  src/components/clip-path-control/index.js
  src/components/clip-path-control/radiusPoint.js
  src/components/clip-path-control/singlePoint.js
  src/components/setting-tabs-control/index.js
  src/components/toolbar/components/column-mover/index.js
  src/components/toolbar/components/columns-handlers/index.js
  src/components/toolbar/components/delete/index.js
  src/components/toolbar/components/duplicate/index.js
  src/components/toolbar/components/help/index.js
  src/components/toolbar/components/more-settings/index.js
  src/components/toolbar/components/mover/index.js
  src/components/toolbar/components/text-bold/index.js
  src/components/toolbar/components/text-format-overline/index.js
  src/components/toolbar/components/text-format-strikethrough/index.js
  src/components/toolbar/components/text-format-subscript/index.js
  src/components/toolbar/components/text-format-superscript/index.js
  src/components/toolbar/components/text-format-underline/index.js
  src/components/toolbar/components/text-italic/index.js
  src/components/toolbar/components/toolbar-popover/index.js
Labels: 😁 final code testing, lgtm, size:M

#5357 Issue 5285 - Move CL to the setings tab for some blocks
  src/blocks/accordion-maxi/inspector.js
  src/blocks/pane-maxi/inspector.js
  src/blocks/slide-maxi/inspector.js
  src/blocks/slider-maxi/inspector.js
Labels: 😁 final code testing, lgtm, size:M

#5358 Issue 5344: speed in Editor
  e2e-tests/blocks/button-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/svg-icon-maxi/__snapshots__/index.spec.js.snap
  src/extensions/style-cards/getPaletteColor.js
  src/extensions/styles/getColorRGBAString.js
  src/extensions/styles/getLastBreakpointAttribute.js
  src/extensions/styles/getPaletteAttributes.js
  src/extensions/styles/helpers/getBackgroundStyles.js
  src/extensions/styles/helpers/getBorderStyles.js
  src/extensions/styles/helpers/getMarginPaddingStyles.js
  src/extensions/styles/helpers/getNumberCounterStyles.js
  src/extensions/styles/helpers/getSVGStyles.js
Labels: 🤠 stable, ⛏ ++ needs deep testing ++ ⛏, 👀 *****fast track***** 👀, 🚀🚀🚀speed🚀🚀🚀, 🌈🌈 next major update 🌈🌈, lgtm, size:XL, 1.5.8

#5347 1.5.8
  changelog.txt
  e2e-tests/blocks/Divider-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/Group-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/button-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/column-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/container-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/number-counter-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/row-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/svg-icon-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/text-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/video-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/components/background/__snapshots__/SVGIconBackground.spec.js.snap
  e2e-tests/components/icon-control/__snapshots__/index.spec.js.snap
  e2e-tests/components/repeater/__snapshots__/index.spec.js.snap
  e2e-tests/components/repeater/content.js
  e2e-tests/components/svg-color/__snapshots__/index.spec.js.snap
  e2e-tests/components/svg-stroke-width-control/__snapshots__/index.spec.js.snap
  e2e-tests/components/video-options-control/__snapshots__/index.spec.js.snap
  languages/maxi-blocks.pot
  plugin.php
  readme.txt
Labels: size:XL

#5366 Issue 5362 - Remove image URL in IB
  src/components/background-control/backgroundLayersControl.js
  src/components/background-control/svgLayer.js
  src/components/svg-fill-control/index.js
Labels: 😁 final code testing, lgtm, size:S
