Repository maxi-blocks/maxi-blocks, pull requests merged in 2023-10, with the labels that each got.

#5170 Issue 5034 - Switch to latest posts for DC and CL if no tags exist on the site and relation is by tag
  core/class-maxi-dynamic-content.php
  src/extensions/DC/getDCOptions.js
  src/extensions/DC/withMaxiContextLoop.js
Labels: 😁 Final Code Testing

#5154 Issue 5097 - dc current post
  core/class-maxi-dynamic-content.php
  src/components/dynamic-content/index.js
  src/components/raw-html/index.js
  src/extensions/DC/constants.js
  src/extensions/DC/getDCContent.js
  src/extensions/DC/getDCEntity.js
  src/extensions/DC/utils.js
  src/extensions/DC/withMaxiDC.js
Labels: 😁 Final Code Testing

#5143 Issue 5017 - Advanced CSS
  core/blocks/style-helpers/get_advanced_css_object.php
  core/blocks/utils/style_processor.php
  e2e-tests/components/custom-css-control/index.spec.js
  e2e-tests/components/custom-css/index.spec.js
  e2e-tests/utils/addCustomCSS.js
  src/blocks/accordion-maxi/attributes.js
  src/blocks/accordion-maxi/inspector.js
  src/blocks/button-maxi/attributes.js
  src/blocks/button-maxi/inspector.js
  src/blocks/column-maxi/attributes.js
  src/blocks/column-maxi/inspector.js
  src/blocks/container-maxi/attributes.js
  src/blocks/container-maxi/inspector.js
  src/blocks/divider-maxi/attributes.js
  src/blocks/divider-maxi/inspector.js
  src/blocks/group-maxi/attributes.js
  src/blocks/group-maxi/inspector.js
  src/blocks/image-maxi/attributes.js
  src/blocks/image-maxi/inspector.js
  src/blocks/map-maxi/attributes.js
  src/blocks/map-maxi/inspector.js
  src/blocks/number-counter-maxi/attributes.js
  src/blocks/number-counter-maxi/inspector.js
  src/blocks/pane-maxi/attributes.js
  src/blocks/pane-maxi/inspector.js
  src/blocks/row-maxi/attributes.js
  src/blocks/row-maxi/inspector.js
  src/blocks/search-maxi/attributes.js
  src/blocks/search-maxi/inspector.js
  src/blocks/slide-maxi/attributes.js
  src/blocks/slide-maxi/inspector.js
  src/blocks/slider-maxi/attributes.js
  src/blocks/slider-maxi/inspector.js
  src/blocks/svg-icon-maxi/attributes.js
  src/blocks/svg-icon-maxi/inspector.js
  src/blocks/text-maxi/attributes.js
  src/blocks/text-maxi/inspector.js
  src/blocks/video-maxi/attributes.js
  src/blocks/video-maxi/inspector.js
  src/components/advanced-css-control/editor.scss
  src/components/advanced-css-control/index.js
  src/components/css-code-editor/editor.scss
  src/components/css-code-editor/index.js
  src/components/custom-css-control/editor.scss
  src/components/custom-css-control/index.js
  src/components/index.js
  src/components/inspector-tabs/index.js
  src/components/inspector-tabs/inspector-advanced-css.js
  src/extensions/styles/defaults/advancedCss.js
  src/extensions/styles/defaults/index.js
  src/extensions/styles/helpers/getAdvancedCssObject.js
  src/extensions/styles/helpers/index.js
  src/extensions/styles/helpers/test/__snapshots__/getAdvancedCssObject.js.snap
  src/extensions/styles/helpers/test/getAdvancedCssObject.js
  src/extensions/styles/styleProcessor.js
Labels: 😁 Final Code Testing

#5177 Issue 5152 - Custom data reset fix
  src/extensions/custom-data/store/controls.js
Labels: 😁 Final Code Testing

#5178 Issue 5140 - `video-maxi`: fix styles for playerType: video
  e2e-tests/blocks/video-maxi/__snapshots__/index.spec.js.snap
  src/blocks/video-maxi/styles.js
Labels: 😁 Final Code Testing

#5182 Issue 5045 - Gutenberg Tablet and Mobile preview fix
  src/extensions/maxi-block/maxiBlockComponent.js
  src/extensions/store/actions.js
  src/extensions/store/reducer.js
  src/extensions/store/selectors.js
Labels: 😁 Final Code Testing

#5174 Issue 5155 - Update `uniqueID` on code editor paste
  e2e-tests/components/repeater/__snapshots__/index.spec.js.snap
  e2e-tests/components/repeater/index.spec.js
  src/blocks/svg-icon-maxi/edit.js
  src/extensions/attributes/uniqueCustomLabelGenerator.js
  src/extensions/attributes/withAttributes.js
  src/extensions/maxi-block/getCustomLabel.js
  src/extensions/maxi-block/getIsUniqueCustomLabelRepeated.js
  src/extensions/maxi-block/maxiBlockComponent.js
  src/extensions/maxi-block/store/actions.js
  src/extensions/maxi-block/store/reducer.js
  src/extensions/maxi-block/store/selectors.js
  src/extensions/maxi-block/test/getCustomLabel.js
Labels: 😁 Final Code Testing

#5175 Issue 5151 - IB. Clip-path for bg layers.
  src/blocks/button-maxi/data.js
  src/blocks/svg-icon-maxi/data.js
  src/components/background-control/backgroundLayersControl.js
  src/components/relation-control/index.js
  src/extensions/maxi-block/cleanAttributes.js
  src/extensions/relations/getCanvasSettings.js
  src/extensions/relations/getCleanDisplayIBAttributes.js
  src/extensions/relations/getTempAttributes.js
  src/extensions/relations/test/getCleanDisplayIBAttributes.js
  src/extensions/styles/getAttributeValue.js
  src/extensions/styles/helpers/getClipPathStyles.js
  src/extensions/styles/helpers/test/__snapshots__/getClipPathStyles.js.snap
Labels: 😁 Final Code Testing

#5053 Issue 4980 - Prompt maxi
  core/admin/admin.js
  core/admin/admin.scss
  core/admin/class-maxi-dashboard.php
  core/class-maxi-api.php
  package-lock.json
  package.json
  src/blocks/map-maxi/utils.js
  src/blocks/text-maxi/edit.js
  src/blocks/text-maxi/inspector.js
  src/components/index.js
  src/components/inspector-tabs/index.js
  src/components/inspector-tabs/inspector-prompt.js
  src/components/prompt-control/components/history-buttons/index.js
  src/components/prompt-control/components/result-card/editor.scss
  src/components/prompt-control/components/result-card/index.js
  src/components/prompt-control/components/result-cards/editor.scss
  src/components/prompt-control/components/result-cards/index.js
  src/components/prompt-control/components/result-modify-bar/editor.scss
  src/components/prompt-control/components/result-modify-bar/index.js
  src/components/prompt-control/constants.js
  src/components/prompt-control/editor.scss
  src/components/prompt-control/hooks/index.js
  src/components/prompt-control/hooks/useAISettings.js
  src/components/prompt-control/hooks/useResultsHandling.js
  src/components/prompt-control/hooks/useSettings.js
  src/components/prompt-control/index.js
  src/components/prompt-control/tabs/generate-tab/editor.scss
  src/components/prompt-control/tabs/generate-tab/index.js
  src/components/prompt-control/tabs/modify-tab/editor.scss
  src/components/prompt-control/tabs/modify-tab/index.js
  src/components/prompt-control/tabs/results-tab/editor.scss
  src/components/prompt-control/tabs/results-tab/index.js
  src/components/prompt-control/utils.js
  src/components/react-select-control/index.js
  src/components/setting-tabs-control/index.js
  src/components/textarea-control/editor.scss
  src/components/textarea-control/index.js
  src/editor/style-cards/maxiStyleCardsEditor.js
  src/editor/style-cards/utils.js
  src/extensions/maxi-block/maxiBlockComponent.js
  src/icons/block-icons/index.js
  src/icons/block-icons/prompt-copy/index.js
  src/icons/block-icons/prompt-copy/promptCopy.svg
  src/icons/block-icons/prompt-delete/index.js
  src/icons/block-icons/prompt-delete/promptDelet.svg
Labels: 😁 Final Code Testing

#5183 Issue 5156 - Fix render for non-DC blocks in EE
  core/blocks/class-maxi-block.php
  e2e-tests/editor/marginValue.spec.js
Labels: 😁 Final Code Testing

#5188 Issue 5181 - fix infinite loop when validating order by attributes
  core/class-maxi-dynamic-content.php
Labels: 😁 Final Code Testing

#5200 Issue 5194 - fix opacity control wrong value when 0
  src/components/opacity-control/index.js
Labels: 😁 final code testing

#5198 Issue 5196 row width
  src/components/inspector-tabs/inspector-size.js
  src/extensions/styles/migrators/blockMigrator.js
  src/extensions/styles/migrators/fullWidthAttributeMigrator.js
Labels: 😁 final code testing

#5204 Fix custom footers and headers for FSE
  core/class-maxi-styles.php
Labels: 🙏 high priority, 😁 final code testing, 👀 *****fast track***** 👀

#5206 Issue 5169 link remove
  src/components/toolbar/components/text-link/index.js
  src/components/toolbar/index.js
Labels: 😁 final code testing

#5210 Move SC migrator
  e2e-tests/blocks/column-maxi/index.spec.js
  e2e-tests/blocks/text-maxi/list.spec.js
  e2e-tests/components/toolbar/components/text-options/index.spec.js
  e2e-tests/editor/style-cards/global.spec.js
  src/components/text-input/index.js
  src/extensions/style-cards/store/controls.js
  src/extensions/style-cards/store/resolvers.js
Labels: 😁 final code testing, 👀 *****fast track***** 👀

#5217 Version 1.5.1
  changelog.txt
  core/admin/admin.scss
  core/admin/class-maxi-dashboard.php
  core/class-maxi-api.php
  core/class-maxi-blocks.php
  core/class-maxi-core.php
  core/class-maxi-page-template.php
  e2e-tests/blocks/Divider-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/Group-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/button-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/column-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/container-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/number-counter-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/row-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/svg-icon-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/text-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/text-maxi/index.spec.js
  e2e-tests/blocks/text-maxi/list.spec.js
  e2e-tests/blocks/video-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/components/background/__snapshots__/SVGIconBackground.spec.js.snap
  e2e-tests/components/background/__snapshots__/shapeLayer.spec.js.snap
  e2e-tests/components/icon-control/__snapshots__/index.spec.js.snap
  e2e-tests/components/repeater/__snapshots__/index.spec.js.snap
  e2e-tests/components/repeater/content.js
  e2e-tests/components/shape-divider/index.spec.js
  e2e-tests/components/svg-color/__snapshots__/index.spec.js.snap
  e2e-tests/components/svg-stroke-width-control/__snapshots__/index.spec.js.snap
  e2e-tests/components/toolbar/components/icon-size/index.spec.js
  e2e-tests/components/video-options-control/__snapshots__/index.spec.js.snap
  e2e-tests/components/video-overlay-control/index.spec.js
  e2e-tests/utils/modalMock.js
  img/maxi-logo-dashboard-white.svg
  languages/maxi-blocks.pot
  license.txt
  plugin.php
  readme.txt
  src/blocks/map-maxi/components/map-content/index.js
  src/blocks/map-maxi/edit.js
  src/blocks/row-maxi/inspector.js
  src/blocks/text-maxi/inspector.js
  src/components/inspector-tabs/inspector-prompt.js
  src/components/prompt-control/components/result-card/index.js
  src/components/prompt-control/hooks/useAISettings.js
  src/components/text-input/index.js
  src/css/editor.scss
  src/editor/auth/index.js
  src/editor/library/editor.scss
  src/editor/library/toolbar.js
  src/editor/saver/index.js
  src/editor/style-cards/maxiStyleCardsEditor.js
  src/editor/toolbar-buttons/index.js
  src/extensions/attributes/withAttributes.js
  src/extensions/maxi-block/maxiBlockComponent.js
  src/extensions/save/index.js
  src/extensions/styles/getLastBreakpointAttribute.js
  src/extensions/text/formats/onChangeRichText.js
Labels: 😁 final code testing, 👀 *****fast track***** 👀

#5216 Issue 5165 - Fix scroll effects
  core/class-maxi-styles.php
  src/extensions/custom-data/store/controls.js
Labels: 😁 final code testing

#5166 Issue 5059 - woocommerce integration
  core/blocks/utils/defaults/dynamicContent.json
  core/class-maxi-api.php
  core/class-maxi-dynamic-content.php
  src/components/dynamic-content/acf-settings-control/index.js
  src/components/dynamic-content/index.js
  src/components/toolbar/components/link/index.js
  src/extensions/DC/constants.js
  src/extensions/DC/getDCContent.js
  src/extensions/DC/getDCEntity.js
  src/extensions/DC/getDCLink.js
  src/extensions/DC/getDCMedia.js
  src/extensions/DC/getDCOptions.js
  src/extensions/DC/getWCContent.js
  src/extensions/DC/getWooCommerceData.js
  src/extensions/DC/utils.js
  src/extensions/DC/withMaxiDC.js
  src/extensions/styles/defaults/dynamicContent.js
Labels: 😁 final code testing

#5220 Fix text generator placeholder colour from grey 1 to 5
  e2e-tests/blocks/text-maxi/list.spec.js
  src/components/toolbar/components/text-generator/editor.scss
Labels: 😁 final code testing
