Repository maxi-blocks/maxi-blocks, pull requests merged in 2024-09, with the labels that each got.

#5715 Custom taxonomies for relations in CL / DC
  core/class-maxi-dynamic-content.php
  core/class-maxi-styles.php
  src/components/context-loop/index.js
  src/components/dynamic-content/acf-settings-control/utils.js
  src/components/dynamic-content/index.js
  src/components/select-control/index.js
  src/extensions/DC/constants.js
  src/extensions/DC/fetchAndUpdateDCData.js
  src/extensions/DC/getDCContent.js
  src/extensions/DC/getDCEntity.js
  src/extensions/DC/getDCOptions.js
  src/extensions/DC/utils.js
  src/extensions/DC/withMaxiContextLoop.js
  src/extensions/DC/withMaxiDC.js
Labels: 🌟 enhancement, Final code review, 🧑‍🚒 need for theme 🧑‍🚒, dynamic content, lgtm, size:XL, 1.9.6

#5713 Issue 5709: styles on insert
  package-lock.json
  package.json
  src/editor/library/utils/onRequestInsertPattern.js
Labels: 👩‍💻 pre-code testing, Final code review, lgtm, size:S, 1.9.6

#5672 Issue 5659 - local fonts on editor
  core/admin/class-maxi-dashboard.php
  core/class-maxi-api.php
  core/class-maxi-local-fonts.php
  core/class-maxi-styles.php
  src/blocks/accordion-maxi/edit.js
  src/blocks/accordion-maxi/inspector.js
  src/blocks/button-maxi/edit.js
  src/blocks/image-maxi/edit.js
  src/blocks/image-maxi/inspector.js
  src/blocks/list-item-maxi/edit.js
  src/blocks/map-maxi/components/map-popup-text-control/index.js
  src/blocks/map-maxi/edit.js
  src/blocks/map-maxi/inspector.js
  src/blocks/number-counter-maxi/components/number-counter-control/index.js
  src/blocks/number-counter-maxi/edit.js
  src/blocks/number-counter-maxi/inspector.js
  src/blocks/search-maxi/edit.js
  src/blocks/text-maxi/edit.js
  src/components/content-loader/index.js
  src/components/font-family-selector/index.js
  src/components/font-weight-control/index.js
  src/components/font-weight-control/utils.js
  src/components/inspector-tabs/inspector-typography.js
  src/components/maxi-block/innerBlocksBlock.js
  src/components/maxi-block/mainMaxiBlock.js
  src/components/maxi-block/maxiBlock.js
  src/components/toolbar/captionToolbar.js
  src/components/toolbar/components/text-options/index.js
  src/components/toolbar/index.js
  src/components/typography-control/index.js
  src/extensions/maxi-block/maxiBlockComponent.js
  src/extensions/text/fonts/loadFonts.js
  src/extensions/text/store/actions.js
  src/extensions/text/store/index.js
  src/extensions/text/store/reducer.js
  src/extensions/text/store/resolvers.js
  src/extensions/text/store/selectors.js
Labels: 🌟 enhancement, Final code review, lgtm, size:L

#5722 Fix reusables inside a column
  src/extensions/attributes/withAttributes.js
Labels: bug 🐛, 🙏 high priority, Final code review, lgtm, size:XS, 1.9.6

#5723 remove performance tests
  .github/workflows/performance-test.yml
  e2e-tests/jest.config.performance.js
  e2e-tests/performance-tests/blocks.perf.js
  e2e-tests/performance-tests/compare/argument-parser.js
  e2e-tests/performance-tests/compare/comparator.js
  e2e-tests/performance-tests/compare/compare.js
  e2e-tests/performance-tests/compare/result-writer.js
  e2e-tests/performance-tests/config.js
  e2e-tests/performance-tests/patterns.perf.js
  e2e-tests/performance-tests/utils.js
  e2e-tests/setup-test-framework.js
Labels: size:XXL

#5733 Issue 5660 - fix wrong `RangeControl` value for 0
  src/components/advanced-number-control/index.js
Labels: bug 🐛, Final code review, lgtm, size:XS

#5732 Issue 5663 - Fix tab labels wrapping on second line when selected
  src/components/setting-tabs-control/editor.scss
Labels: bug 🐛, Final code review, lgtm, size:XS

#5728 Issue 5457 - Fix insert button disappearing when using DC link in icon maxi
  src/components/toolbar/components/media-upload/index.js
Labels: bug 🐛, Final code review, lgtm, size:XS

#5730 Issue 5701 - add limit option to all text fields
  src/extensions/DC/constants.js
  src/extensions/DC/getWCContent.js
Labels: 🌟 enhancement, Final code review, lgtm, size:S

#5731 Issue 5703 - Fix DC blocks breaking when no tags are found
  src/extensions/DC/getDCContent.js
Labels: bug 🐛, Final code review, lgtm, size:XS

#5725 Issue 4882 - fix local fonts preload warning
  core/class-maxi-styles.php
Labels: bug 🐛, Final code review, lgtm, size:M

#5724 Issue 5446 - Fix accordion styles not loading until some change
  src/blocks/pane-maxi/edit.js
Labels: bug 🐛, Final code review, lgtm, size:S

#5727 Issue 5486 - Hide "ACF Field" dropdown for CL
  src/components/dynamic-content/acf-settings-control/index.js
Labels: bug 🐛, Final code review, lgtm, size:M

#5742 update dompurify
  package-lock.json
Labels: Final code review, lgtm, size:XS

#5743 1.9.6
  changelog.txt
  e2e-tests/blocks/Divider-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/Group-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/button-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/column-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/container-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/number-counter-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/row-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/svg-icon-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/text-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/video-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/components/background/__snapshots__/SVGIconBackground.spec.js.snap
  e2e-tests/components/icon-control/__snapshots__/index.spec.js.snap
  e2e-tests/components/repeater/__snapshots__/index.spec.js.snap
  e2e-tests/components/repeater/content.js
  e2e-tests/components/svg-color/__snapshots__/index.spec.js.snap
  e2e-tests/components/svg-stroke-width-control/__snapshots__/index.spec.js.snap
  e2e-tests/components/video-options-control/__snapshots__/index.spec.js.snap
  languages/maxi-blocks.pot
  plugin.php
  readme.txt
Labels: size:L

#5746 Fix DC not showing 'by category' and other dropdowns
  src/components/dynamic-content/index.js
Labels: Final code review, lgtm, size:M

#5747 Add Theme tab to Template Library
  src/editor/library/container.js
Labels: 🌟 enhancement, Final code review, lgtm, size:XS

#5749 Issue 5748 responsive
  core/class-maxi-styles.php
  src/extensions/maxi-block/maxiBlockComponent.js
  src/extensions/styles/helpers/getBreakpoints.js
  src/extensions/styles/store/controls.js
Labels: bug 🐛, Final code review, lgtm, size:M

#5750 1.9.7
  changelog.txt
  e2e-tests/blocks/Divider-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/Group-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/button-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/column-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/container-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/number-counter-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/row-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/svg-icon-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/text-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/video-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/components/background/__snapshots__/SVGIconBackground.spec.js.snap
  e2e-tests/components/icon-control/__snapshots__/index.spec.js.snap
  e2e-tests/components/repeater/__snapshots__/index.spec.js.snap
  e2e-tests/components/repeater/content.js
  e2e-tests/components/svg-color/__snapshots__/index.spec.js.snap
  e2e-tests/components/svg-stroke-width-control/__snapshots__/index.spec.js.snap
  e2e-tests/components/video-options-control/__snapshots__/index.spec.js.snap
  languages/maxi-blocks.pot
  plugin.php
  readme.txt
Labels: size:S

#5753 Issue 5752 dark link
  core/class-maxi-style-cards.php
  core/defaults/defaultSC.json
  core/defaults/sc_defaults.php
  src/editor/library/container.js
Labels: Final code review, lgtm, size:L, 1.9.8

#5754 Issue 5751 tone
  src/extensions/maxi-block/maxiBlockComponent.js
Labels: bug 🐛, Final code review, lgtm, size:S, 1.9.8

#5755 1.9.8
  changelog.txt
  core/class-maxi-style-cards.php
  e2e-tests/blocks/Divider-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/Group-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/button-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/column-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/container-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/number-counter-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/row-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/svg-icon-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/text-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/video-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/components/background/__snapshots__/SVGIconBackground.spec.js.snap
  e2e-tests/components/icon-control/__snapshots__/index.spec.js.snap
  e2e-tests/components/repeater/__snapshots__/index.spec.js.snap
  e2e-tests/components/repeater/content.js
  e2e-tests/components/svg-color/__snapshots__/index.spec.js.snap
  e2e-tests/components/svg-stroke-width-control/__snapshots__/index.spec.js.snap
  e2e-tests/components/video-options-control/__snapshots__/index.spec.js.snap
  languages/maxi-blocks.pot
  plugin.php
  readme.txt
Labels: size:S, 1.9.8
