Repository maxi-blocks/maxi-blocks, pull requests merged in 2024-06, with the labels that each got.

#5601 Issue 5598: typography unit revert
  e2e-tests/components/typography-control/index.spec.js
  src/extensions/styles/migrators/blockMigrator.js
  src/extensions/styles/migrators/typographyUnitsDefaultsMigrator.js
  src/extensions/styles/typographyAttributesCreator.js
Labels: lgtm, size:L

#5597 For theme vol 4
  core/admin/admin.js
  core/admin/admin.scss
  core/class-maxi-api.php
  core/class-maxi-blocks.php
  core/class-maxi-dynamic-content.php
  core/class-maxi-styles.php
  core/defaults/defaultSC.json
  e2e-tests/editor/__snapshots__/sc-variable.spec.js.snap
  e2e-tests/editor/style-cards/__snapshots__/button.spec.js.snap
  e2e-tests/editor/style-cards/__snapshots__/link.spec.js.snap
  e2e-tests/editor/style-cards/link.spec.js
  e2e-tests/utils/editGlobalStyles.js
  src/editor/library/container.js
  src/extensions/maxi-block/goThroughMaxiBlocks.js
  src/extensions/maxi-block/withMaxiLoader.js
  src/extensions/style-cards/getSCStyles.js
  src/extensions/style-cards/test/__snapshots__/getSCStyles.js.snap
  src/extensions/style-cards/test/__snapshots__/getSCVariablesObject.js.snap
  src/extensions/style-cards/test/__snapshots__/updateSCOnEditor.js.snap
  src/extensions/style-cards/updateSCOnEditor.js
  src/extensions/text/fonts/utils.js
Labels: 🙏 high priority, Final code review, lgtm, size:L, 1.8.8

#5606 Issue 5570 5571
  core/class-maxi-api.php
  core/class-maxi-styles.php
  src/editor/toolbar-buttons/index.js
  src/extensions/dom/getCurrentPreviewDeviceType.js
  src/extensions/maxi-block/goThroughMaxiBlocks.js
  src/extensions/maxi-block/maxiBlockComponent.js
  src/extensions/store/reducer.js
Labels: bug 🐛, 🙏 high priority, Final code review, 🧑‍🚒 need for theme 🧑‍🚒, lgtm, size:L, 1.8.8

#5613 Issue 5383: plugin check
  core/admin/class-maxi-dashboard.php
  core/blocks/class-maxi-block.php
  core/blocks/utils/get_block_attributes.php
  core/blocks/utils/get_default_attribute.php
  core/blocks/utils/get_group_attributes.php
  core/blocks/utils/style_resolver.php
  core/class-maxi-api.php
  core/class-maxi-blocks.php
  core/class-maxi-core.php
  core/class-maxi-dynamic-content.php
  core/class-maxi-image-crop.php
  core/class-maxi-local-fonts.php
  core/class-maxi-style-cards.php
  core/class-maxi-styles.php
  core/utils/get-last-breakpoint-attribute.php
  plugin.php
Labels: 🙏 high priority, 👩‍💻 pre-code testing, Final code review, lgtm, size:XXL, 1.8.9

#5620 attempt to fix deploy
  .github/workflows/update-staging-maximaster.yml
Labels: size:XS

#5621 revert one time fix for deploy
  .github/workflows/update-staging-maximaster.yml
Labels: 👩‍💻 pre-code testing, size:XS

#5600 Issue 4811 - DC for background image
  core/blocks/class-maxi-block.php
  core/class-maxi-dynamic-content.php
  e2e-tests/components/background/__snapshots__/imageLayer.spec.js.snap
  src/blocks/accordion-maxi/edit.js
  src/blocks/column-maxi/edit.js
  src/blocks/container-maxi/edit.js
  src/blocks/group-maxi/edit.js
  src/blocks/list-item-maxi/edit.js
  src/blocks/map-maxi/edit.js
  src/blocks/number-counter-maxi/edit.js
  src/blocks/pane-maxi/edit.js
  src/blocks/row-maxi/edit.js
  src/blocks/search-maxi/edit.js
  src/blocks/slide-maxi/edit.js
  src/blocks/svg-icon-maxi/edit.js
  src/blocks/video-maxi/edit.js
  src/components/background-control/backgroundLayersControl.js
  src/components/background-control/imageLayer.js
  src/components/background-control/utils.js
  src/components/background-displayer/index.js
  src/components/dynamic-content/index.js
  src/components/inspector-tabs/inspector-dc.js
  src/components/toolbar/index.js
  src/extensions/DC/fetchAndUpdateDCData.js
  src/extensions/DC/withMaxiDC.js
  src/extensions/maxi-block/maxiBlockComponent.js
  src/extensions/styles/defaults/background.js
  src/extensions/styles/helpers/getBackgroundStyles.js
  src/extensions/styles/utils.js
Labels: 🌟 enhancement, Final code review, lgtm, size:XL, 1.9.0

#5622 1.8.9
  changelog.txt
  core/class-maxi-dynamic-content.php
  core/defaults/defaultSC.json
  e2e-tests/blocks/Divider-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/Group-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/button-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/column-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/container-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/number-counter-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/row-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/svg-icon-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/text-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/video-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/components/background/__snapshots__/SVGIconBackground.spec.js.snap
  e2e-tests/components/icon-control/__snapshots__/index.spec.js.snap
  e2e-tests/components/repeater/__snapshots__/index.spec.js.snap
  e2e-tests/components/repeater/content.js
  e2e-tests/components/svg-color/__snapshots__/index.spec.js.snap
  e2e-tests/components/svg-stroke-width-control/__snapshots__/index.spec.js.snap
  e2e-tests/components/video-options-control/__snapshots__/index.spec.js.snap
  e2e-tests/editor/__snapshots__/sc-variable.spec.js.snap
  e2e-tests/editor/style-cards/__snapshots__/link.spec.js.snap
  e2e-tests/editor/style-cards/link.spec.js
  e2e-tests/utils/editGlobalStyles.js
  languages/maxi-blocks.pot
  plugin.php
  readme.txt
  src/extensions/style-cards/test/__snapshots__/getSCVariablesObject.js.snap
  src/extensions/style-cards/test/__snapshots__/updateSCOnEditor.js.snap
Labels: size:XL

#5626 1.9.0
  changelog.txt
  core/class-maxi-dynamic-content.php
  e2e-tests/blocks/Divider-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/Group-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/button-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/column-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/container-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/number-counter-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/row-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/svg-icon-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/text-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/video-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/components/background/__snapshots__/SVGIconBackground.spec.js.snap
  e2e-tests/components/background/__snapshots__/imageLayer.spec.js.snap
  e2e-tests/components/icon-control/__snapshots__/index.spec.js.snap
  e2e-tests/components/repeater/__snapshots__/index.spec.js.snap
  e2e-tests/components/repeater/content.js
  e2e-tests/components/svg-color/__snapshots__/index.spec.js.snap
  e2e-tests/components/svg-stroke-width-control/__snapshots__/index.spec.js.snap
  e2e-tests/components/video-options-control/__snapshots__/index.spec.js.snap
  plugin.php
  readme.txt
Labels: size:M

#5614 Issue 5464: IB SEO score on frontend
  core/class-maxi-styles.php
  e2e-tests/components/background/__snapshots__/imageLayer.spec.js.snap
  e2e-tests/components/relation-control/__snapshots__/button-maxi.spec.js.snap
  js/maxi-relations.js
Labels: optimization, 🙏 high priority, 👩‍💻 pre-code testing, Final code review, interaction builder, lgtm, size:L, Woo, 1.9.1

#5617 Fronted stripts optimization
  core/class-maxi-styles.php
  js/maxi-number-counter.js
  js/maxi-parallax.js
  js/maxi-video.js
Labels: optimization, 👩‍💻 pre-code testing, Final code review, lgtm, size:XL, 1.9.1

#5633 Issue 5630: Fix Woo CL not hiding empty items
  core/class-maxi-dynamic-content.php
  e2e-tests/components/background/__snapshots__/imageLayer.spec.js.snap
Labels: bug 🐛, 🙏 need for library, Final code review, lgtm, size:XS, 1.9.1
