Repository maxi-blocks/maxi-blocks, pull requests merged in 2024-01, with the labels that each got.

#5223 Issue 5100 - hide DC blocks on frontend
  core/blocks/class-maxi-block.php
  core/class-maxi-dynamic-content.php
  src/components/dynamic-content/index.js
  src/components/maxi-block/getMaxiBlockAttributes.js
  src/components/maxi-block/maxiBlock.js
  src/css/style.scss
  src/extensions/DC/utils.js
  src/extensions/DC/withMaxiDC.js
  src/extensions/styles/defaults/dynamicContent.js
  src/extensions/styles/migrators/DCClassNameMigrator.js
  src/extensions/styles/migrators/blockMigrator.js
Labels: 😁 Final code review 🖖, lgtm, size:L

#5364 Issue 5352 - Advanced CSS class
  e2e-tests/utils/addCustomCSS.js
  src/components/css-code-editor/index.js
  src/components/custom-css-control/index.js
Labels: 😁 Final code review 🖖, size:M

#5375 Issue 5195 - UI fixes Round 2
  src/components/background-control/editor.scss
  src/components/font-level-control/editor.scss
  src/components/overflow-control/editor.scss
  src/components/setting-tabs-control/editor.scss
  src/components/transform-control/editor.scss
Labels: Final code review, size:M

#5371 Fix 5370 - `text-maxi` crash on `TypographyControl` fast open
  src/components/font-weight-control/index.js
Labels: Final code review, size:XS

#5367 Issue 5136 - Dashboard responsive
  core/admin/admin.scss
Labels: Final code review, size:S

#5340 Issue 5312 - Fix parallax and shape divider frontend
  core/class-maxi-styles.php
  js/maxi-parallax.js
  js/maxi-shape-divider.js
  src/components/background-displayer/index.js
  src/components/custom-css-control/utils.js
  src/components/inspector-tabs/inspector-transform.js
  src/components/transform-control/utils.js
  src/extensions/styles/styleProcessor.js
Labels: Final code review, lgtm, size:L

#5172 Issue 4992 - typography responsive bug
  e2e-tests/blocks/button-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/column-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/column-maxi/index.spec.js
  e2e-tests/blocks/row-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/components/background/__snapshots__/colorLayer.spec.js.snap
  e2e-tests/components/background/__snapshots__/gradientLayer.spec.js.snap
  e2e-tests/components/background/__snapshots__/imageLayer.spec.js.snap
  e2e-tests/components/background/__snapshots__/shapeLayer.spec.js.snap
  e2e-tests/components/background/__snapshots__/videoLayer.spec.js.snap
  e2e-tests/components/repeater/__snapshots__/index.spec.js.snap
  e2e-tests/editor/style-cards/__snapshots__/button.spec.js.snap
  e2e-tests/editor/style-cards/__snapshots__/headings.spec.js.snap
  e2e-tests/editor/style-cards/__snapshots__/paragraph.spec.js.snap
  src/extensions/maxi-block/cleanAttributes.js
  src/extensions/maxi-block/handleSetAttributes.js
  src/extensions/maxi-block/test/cleanAttributes.js
  src/extensions/text/formats/flatFormatsWithClass.js
  src/extensions/text/formats/removeLinkFormat.js
  src/extensions/text/formats/setFormat.js
  src/extensions/text/formats/setFormatWithClass.js
  src/extensions/text/formats/test/flatFormatsWithClass.js
  src/extensions/text/formats/test/setFormatWithClass.js
  src/extensions/text/formats/updateCustomFormatStyle.js
Labels: Final code review, size:L

#5381 Issue 5380: Fix migrators bug with uniqueID
  src/extensions/attributes/getClientIdFromUniqueId.js
  src/extensions/relations/Relation.js
  src/extensions/styles/migrators/SVGIBTargetsMigrator.js
  src/extensions/styles/migrators/utils.js
Labels: Final code review, lgtm, size:XS

#5356 Issue 5277 - RTL 03
  e2e-tests/blocks/text-maxi/__snapshots__/list.spec.js.snap
  src/blocks/cloud-maxi/editor.scss
  src/blocks/pane-maxi/style.scss
  src/blocks/row-maxi/editor.scss
  src/blocks/text-maxi/editor.scss
  src/blocks/text-maxi/style.scss
  src/blocks/text-maxi/styles.js
  src/components/toolbar/components/column-pattern/editor.scss
Labels: front testing, Final code review, lgtm, size:M

#5385 Move border to show cursor
  src/css/editor.scss
Labels: Final code review, 👀 *****fast track***** 👀, mvp legacy :hammer_and_wrench:, mvp fix :fast_forward:, lgtm, size:XS

#5368 Issue 5360 - Fix styles on block tone change
  src/components/block-styles-control/index.js
  src/extensions/attributes/withAttributes.js
  src/extensions/maxi-block/maxiBlockComponent.js
  src/extensions/styles/store/actions.js
  src/extensions/styles/store/reducer.js
Labels: Final code review, lgtm, size:L

#5335 Issue 5316 - Making translations better
  core/admin/class-maxi-dashboard.php
  e2e-tests/components/video-icon-control/index.spec.js
  languages/maxi-blocks.pot
  src/components/clip-path-control/doublePoint.js
  src/components/clip-path-control/radiusPoint.js
  src/components/clip-path-control/singlePoint.js
  src/components/color-control/paletteControl.js
Labels: Final code review, lgtm, size:L

#5387 Issue 5386 - Block tone fix for blocks with IB
  src/components/toolbar/components/copy-paste/index.js
  src/extensions/attributes/getUpdatedBGLayersWithNewUniqueID.js
  src/extensions/maxi-block/maxiBlockComponent.js
  src/extensions/maxi-block/propagateNewUniqueID.js
  src/extensions/maxi-block/store/actions.js
  src/extensions/maxi-block/store/reducer.js
  src/extensions/maxi-block/store/selectors.js
Labels: Final code review, mvp legacy :hammer_and_wrench:, mvp fix :fast_forward:, lgtm, size:L, 1.5.9

#5382 Issue 5361 - Support Yoast Duplicate Post plugin duplicate
  core/class-maxi-styles.php
Labels: Final code review, mvp legacy :hammer_and_wrench:, mvp fix :fast_forward:, size:L, 1.5.9

#5390 WP 6.4.2 tests
  .wp-env.json
  e2e-tests/blocks/text-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/text-maxi/index.spec.js
  e2e-tests/blocks/text-maxi/list.spec.js
Labels: 👩‍💻 pre-code testing, size:S

#5391 Issue 5353 & 5310 - Fix IB on repeater toggle
  core/class-maxi-dynamic-content.php
  src/components/relation-control/index.js
  src/components/repeater/index.js
  src/extensions/DC/getDCEntity.js
  src/extensions/maxi-block/maxiBlockComponent.js
  src/extensions/maxi-block/propagateNewUniqueID.js
  src/extensions/repeater/validateRowColumnsStructure.js
Labels: Final code review, lgtm, size:L

#5394 1.6.0
  changelog.txt
  e2e-tests/blocks/Divider-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/Group-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/button-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/column-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/container-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/number-counter-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/row-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/svg-icon-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/text-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/video-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/components/background/__snapshots__/SVGIconBackground.spec.js.snap
  e2e-tests/components/icon-control/__snapshots__/index.spec.js.snap
  e2e-tests/components/repeater/__snapshots__/index.spec.js.snap
  e2e-tests/components/repeater/content.js
  e2e-tests/components/svg-color/__snapshots__/index.spec.js.snap
  e2e-tests/components/svg-stroke-width-control/__snapshots__/index.spec.js.snap
  e2e-tests/components/video-options-control/__snapshots__/index.spec.js.snap
  languages/maxi-blocks.pot
  plugin.php
  readme.txt
Labels: 👩‍💻 pre-code testing, size:L

#5396 Issue 4629 - Fix caption content reset after setting change
  src/blocks/image-maxi/edit.js
Labels: bug 🐛, Final code review, lgtm, size:XS

#5401 Fix FSE previews render
  src/extensions/DC/withMaxiContextLoop.js
  src/extensions/attributes/withAttributes.js
  src/extensions/dom/dom.js
  src/extensions/fse/getSiteEditorPreviewIframes.js
  src/extensions/fse/getSiteEditorPreviewIframesBodies.js
  src/extensions/fse/index.js
  src/extensions/maxi-block/maxiBlockComponent.js
  src/extensions/relations/updateRelationsRemotely.js
  src/extensions/style-cards/updateSCOnEditor.js
Labels: 🙏 high priority, Final code review, 🧑‍🚒 need for theme 🧑‍🚒, lgtm, size:L, 1.6.1, fse

#5399 Issue 5303 - Fix scale scroll effect
  js/maxi-scroll-effects.js
Labels: bug 🐛, Final code review, lgtm, size:L

#5395 Issue 5176 - Fix image-maxi shape mask for DC
  src/blocks/image-maxi/edit.js
  src/blocks/image-maxi/save.js
  src/components/dynamic-content/index.js
  src/components/inspector-tabs/inspector-dc.js
  src/components/toolbar/components/dynamic-content/index.js
  src/components/toolbar/components/media-upload/index.js
  src/components/toolbar/index.js
  src/extensions/DC/getDCImgSVG.js
  src/extensions/DC/index.js
  src/extensions/DC/withMaxiDC.js
  src/extensions/svg/getUpdatedImgSVG.js
  src/extensions/svg/index.js
  src/extensions/svg/injectImgSVG.js
Labels: Final code review, lgtm, size:L

#5397 Issue 5393 - DC avatar support
  core/class-maxi-dynamic-content.php
  src/blocks/image-maxi/edit.js
  src/components/dynamic-content/index.js
  src/extensions/DC/constants.js
  src/extensions/DC/getDCMedia.js
  src/extensions/DC/withMaxiDC.js
Labels: bug 🐛, Final code review, lgtm, size:M

#5412 Issue 5411 - Fix font-style Array to string conversion warning
  core/class-maxi-styles.php
Labels: Final code review, lgtm, size:XS
