Repository maxi-blocks/maxi-blocks, pull requests merged in 2024-05, with the labels that each got.

#5576 Site bugs
  core/class-maxi-dynamic-content.php
  src/components/context-loop/index.js
  src/components/maxi-block/maxiBlock.js
  src/extensions/style-cards/getSCStyles.js
  src/extensions/style-cards/test/__snapshots__/getSCStyles.js.snap
Labels: bug 🐛, 👩‍💻 pre-code testing, Final code review, lgtm, size:M, 1.8.4

#5575 Issue 5561: pagination and repeated CL content
  core/blocks/class-maxi-block.php
  core/class-maxi-dynamic-content.php
  src/blocks/divider-maxi/attributes.js
  src/blocks/divider-maxi/edit.js
  src/blocks/divider-maxi/inspector.js
  src/blocks/row-maxi/style.scss
  src/blocks/text-maxi/edit.js
  src/blocks/text-maxi/save.js
  src/components/context-loop/index.js
  src/components/toolbar/components/dynamic-content/index.js
  src/components/toolbar/components/text-link/index.js
  src/extensions/DC/constants.js
  src/extensions/styles/defaults/contextLoop.js
Labels: 👩‍💻 pre-code testing, Final code review, 🧑‍🚒 need for theme 🧑‍🚒, lgtm, size:L, 1.8.4

#5580 Issue 5577: dc content
  core/class-maxi-dynamic-content.php
Labels: 👩‍💻 pre-code testing, Final code review, 🧑‍🚒 need for theme 🧑‍🚒, lgtm, size:M, 1.8.4

#5578 Issue 5561: woo and custom post types
  core/class-maxi-dynamic-content.php
  src/components/context-loop/index.js
  src/components/dynamic-content/acf-settings-control/index.js
  src/components/dynamic-content/index.js
Labels: 👩‍💻 pre-code testing, Final code review, lgtm, size:L

#5574 Issue 5486 - validation for ACF DC attributes
  src/components/context-loop/index.js
  src/components/dynamic-content/acf-settings-control/index.js
  src/components/dynamic-content/acf-settings-control/utils.js
  src/components/dynamic-content/index.js
  src/extensions/DC/getACFData.js
  src/extensions/DC/getDCMedia.js
  src/extensions/DC/getTypes.js
  src/extensions/DC/store/actions.js
  src/extensions/DC/store/index.js
  src/extensions/DC/store/reducer.js
  src/extensions/DC/store/resolvers.js
  src/extensions/DC/store/selectors.js
  src/extensions/DC/utils.js
  src/extensions/DC/validateDCAttributes.js
Labels: bug 🐛, Final code review, lgtm, size:L

#5572 1.8.4
  changelog.txt
  core/blocks/class-maxi-block.php
  core/class-maxi-api.php
  core/class-maxi-dynamic-content.php
  e2e-tests/blocks/Divider-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/Group-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/button-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/column-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/container-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/number-counter-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/row-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/svg-icon-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/text-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/video-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/components/background/__snapshots__/SVGIconBackground.spec.js.snap
  e2e-tests/components/icon-control/__snapshots__/index.spec.js.snap
  e2e-tests/components/repeater/__snapshots__/index.spec.js.snap
  e2e-tests/components/repeater/content.js
  e2e-tests/components/svg-color/__snapshots__/index.spec.js.snap
  e2e-tests/components/svg-stroke-width-control/__snapshots__/index.spec.js.snap
  e2e-tests/components/video-options-control/__snapshots__/index.spec.js.snap
  js/maxi-relations.js
  languages/maxi-blocks.pot
  plugin.php
  readme.txt
  src/components/context-loop/index.js
  src/components/dynamic-content/acf-settings-control/index.js
  src/components/dynamic-content/acf-settings-control/utils.js
  src/components/dynamic-content/index.js
  src/extensions/DC/index.js
  src/extensions/DC/showStaticOption.js
  src/extensions/DC/utils.js
  src/extensions/attributes/withAttributes.js
  src/extensions/maxi-block/withMaxiLoader.js
  src/extensions/maxi-block/withMaxiPreview.js
Labels: 👩‍💻 pre-code testing, size:XL

#5582 Issue 5581 - Fix list-item-maxi double link
  src/blocks/list-item-maxi/index.js
  src/extensions/save/index.js
  src/extensions/styles/migrators/index.js
  src/extensions/styles/migrators/listItemDoubleLinkMigrator.js
Labels: bug 🐛, Final code review, lgtm, size:L, 1.8.5

#5583 1.8.5
  changelog.txt
  e2e-tests/blocks/Divider-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/Group-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/button-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/column-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/container-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/number-counter-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/row-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/svg-icon-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/text-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/video-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/components/background/__snapshots__/SVGIconBackground.spec.js.snap
  e2e-tests/components/icon-control/__snapshots__/index.spec.js.snap
  e2e-tests/components/repeater/__snapshots__/index.spec.js.snap
  e2e-tests/components/repeater/content.js
  e2e-tests/components/svg-color/__snapshots__/index.spec.js.snap
  e2e-tests/components/svg-stroke-width-control/__snapshots__/index.spec.js.snap
  e2e-tests/components/video-options-control/__snapshots__/index.spec.js.snap
  languages/maxi-blocks.pot
  plugin.php
  readme.txt
Labels: size:M

#5579 Issue 5499 - wrong unit from SC shown in typography settings
  e2e-tests/blocks/button-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/components/relation-control/__snapshots__/button-maxi.spec.js.snap
  e2e-tests/components/typography-control/index.spec.js
  e2e-tests/editor/responsive.spec.js
  e2e-tests/editor/style-cards/__snapshots__/button.spec.js.snap
  e2e-tests/editor/style-cards/__snapshots__/headings.spec.js.snap
  e2e-tests/editor/style-cards/__snapshots__/paragraph.spec.js.snap
  src/components/typography-control/index.js
  src/editor/style-cards/maxiStyleCardsEditor.js
  src/extensions/maxi-block/cleanAttributes.js
  src/extensions/maxi-block/handleSetAttributes.js
  src/extensions/maxi-block/test/cleanAttributes.js
  src/extensions/relations/getCleanDisplayIBAttributes.js
  src/extensions/relations/getCleanResponseIBAttributes.js
  src/extensions/relations/getRelatedAttributes.js
  src/extensions/style-cards/getSCVariablesObject.js
  src/extensions/style-cards/utils.js
  src/extensions/styles/getBreakpointFromAttribute.js
  src/extensions/styles/getDefaultAttribute.js
  src/extensions/styles/migrators/transformMigrator.js
  src/extensions/styles/test/getBreakpointFromAttribute.js
  src/extensions/styles/typographyAttributesCreator.js
  src/extensions/styles/utils.js
Labels: bug 🐛, Final code review, lgtm, size:L

#5590 Pagination hidden content fix
  core/blocks/class-maxi-block.php
  core/class-maxi-dynamic-content.php
Labels: bug 🐛, 🙏 high priority, Final code review, lgtm, size:L, 1.8.6

#5594 Issue 5593: cl categories
  core/class-maxi-dynamic-content.php
  src/extensions/maxi-block/maxiBlockComponent.js
Labels: bug 🐛, 🙏 high priority, Final code review, lgtm, size:S, 1.8.7

#5595 1.8.7
  changelog.txt
  core/class-maxi-dynamic-content.php
  e2e-tests/blocks/Divider-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/Group-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/button-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/column-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/container-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/number-counter-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/row-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/svg-icon-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/text-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/video-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/components/background/__snapshots__/SVGIconBackground.spec.js.snap
  e2e-tests/components/icon-control/__snapshots__/index.spec.js.snap
  e2e-tests/components/repeater/__snapshots__/index.spec.js.snap
  e2e-tests/components/repeater/content.js
  e2e-tests/components/svg-color/__snapshots__/index.spec.js.snap
  e2e-tests/components/svg-stroke-width-control/__snapshots__/index.spec.js.snap
  e2e-tests/components/video-options-control/__snapshots__/index.spec.js.snap
  languages/maxi-blocks.pot
  plugin.php
  readme.txt
  src/extensions/maxi-block/maxiBlockComponent.js
Labels: size:M
