Repository maxi-blocks/maxi-blocks, pull requests merged in 2024-07, with the labels that each got.

#5638 Issue 5637: Fix search icon replace
  src/components/icon-control/index.js
Labels: bug 🐛, Final code review, lgtm, size:S

#5645 Issue 5587: cpt template
  core/class-maxi-dynamic-content.php
  e2e-tests/components/background/__snapshots__/imageLayer.spec.js.snap
  src/components/dynamic-content/index.js
  src/components/toolbar/components/link/index.js
  src/extensions/DC/fetchAndUpdateDCData.js
  src/extensions/DC/getDCContent.js
  src/extensions/DC/getDCEntity.js
  src/extensions/DC/getDCLink.js
  src/extensions/DC/getDCOptions.js
  src/extensions/DC/utils.js
Labels: 🌟 enhancement, 👩‍💻 pre-code testing, Final code review, 🧑‍🚒 need for theme 🧑‍🚒, lgtm, size:L, 1.9.1

#5640 WordPress 6.6 fixes
  .babelrc.js
  e2e-tests/components/background/__snapshots__/imageLayer.spec.js.snap
  package-lock.json
  package.json
  src/blocks/column-maxi/editor.scss
  src/blocks/map-maxi/editor.scss
  src/components/block-inserter/index.js
  src/components/popover/index.js
  src/css/editor.scss
  src/css/inserter-card.scss
  src/css/maxi-themes-banner.scss
  src/editor/library/container.js
  src/editor/library/editor.scss
  src/editor/responsive-selector/editor.scss
  src/editor/responsive-selector/index.js
  src/editor/toolbar-buttons/index.js
  src/extensions/DC/getDCEntity.js
  src/extensions/dom/dom.js
  src/extensions/fse/getSiteEditorIframe.js
  src/extensions/relations/Relation.js
  src/extensions/store/reducer.js
  webpack.config.js
Labels: bug 🐛, 🌟 enhancement, dependencies, 👩‍💻 pre-code testing, Final code review, ⛏ ++ needs deep testing ++ ⛏, 🌈🌈 next major update 🌈🌈, lgtm, size:L, 1.9.2

#5649 Issue 5639: close icon search
  src/editor/library/container.js
Labels: bug 🐛, Final code review, lgtm, size:XS, 1.9.2

#5650 Issue 5647: mobile bg
  core/defaults/defaultSC.json
  core/defaults/sc_defaults.php
  e2e-tests/editor/__snapshots__/sc-variable.spec.js.snap
  src/editor/library/container.js
  src/extensions/style-cards/store/selectors.js
  src/extensions/style-cards/test/__snapshots__/getSCVariablesObject.js.snap
  src/extensions/style-cards/test/__snapshots__/updateSCOnEditor.js.snap
Labels: 🌟 enhancement, Final code review, lgtm, size:M, 1.9.2

#5651 Issue 5641: Remove blue line for typography
  src/components/toolbar/editor.scss
Labels: Final code review, lgtm, size:M, 1.9.2

#5652 Issue 5648 - Fix custom fonts not loading on frontend
  src/extensions/text/fonts/test/utils.js
  src/extensions/text/fonts/utils.js
Labels: bug 🐛, Final code review, lgtm, size:L, 1.9.2

#5655 Issue 5654: cloud sc default
  src/editor/library/container.js
  src/extensions/style-cards/store/selectors.js
Labels: 👩‍💻 pre-code testing, Final code review, lgtm, size:L, 1.9.2

#5656 Fix the failing imageLayer.spec.js test
  e2e-tests/components/background/__snapshots__/imageLayer.spec.js.snap
  src/components/dynamic-content/index.js
Labels: 🙏 high priority, test, Final code review, lgtm, size:XS

#5657 1.9.2
  changelog.txt
  core/class-maxi-dynamic-content.php
  core/class-maxi-style-cards.php
  e2e-tests/blocks/Divider-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/Group-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/button-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/column-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/container-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/number-counter-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/row-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/svg-icon-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/text-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/video-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/components/background/__snapshots__/SVGIconBackground.spec.js.snap
  e2e-tests/components/icon-control/__snapshots__/index.spec.js.snap
  e2e-tests/components/repeater/__snapshots__/index.spec.js.snap
  e2e-tests/components/repeater/content.js
  e2e-tests/components/svg-color/__snapshots__/index.spec.js.snap
  e2e-tests/components/svg-stroke-width-control/__snapshots__/index.spec.js.snap
  e2e-tests/components/video-options-control/__snapshots__/index.spec.js.snap
  languages/maxi-blocks.pot
  plugin.php
  readme.txt
  src/extensions/DC/getDCEntity.js
  src/extensions/style-cards/getSCStyles.js
  src/extensions/style-cards/test/__snapshots__/getSCStyles.js.snap
Labels: Final code review, lgtm, size:L

#5662 Issue 5138, 4959 - Fix fonts not loading for some maxi blocks
  src/extensions/text/fonts/test/utils.js
  src/extensions/text/fonts/utils.js
Labels: 👩‍💻 pre-code testing, Final code review, lgtm, size:L

#5665 1.9.3
  changelog.txt
  core/class-maxi-image-crop.php
  e2e-tests/blocks/Divider-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/Group-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/button-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/column-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/container-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/number-counter-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/row-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/svg-icon-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/text-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/video-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/components/background/__snapshots__/SVGIconBackground.spec.js.snap
  e2e-tests/components/icon-control/__snapshots__/index.spec.js.snap
  e2e-tests/components/repeater/__snapshots__/index.spec.js.snap
  e2e-tests/components/repeater/content.js
  e2e-tests/components/svg-color/__snapshots__/index.spec.js.snap
  e2e-tests/components/svg-stroke-width-control/__snapshots__/index.spec.js.snap
  e2e-tests/components/video-options-control/__snapshots__/index.spec.js.snap
  languages/maxi-blocks.pot
  plugin.php
  readme.txt
  src/extensions/dom/dom.js
Labels: bug 🐛, Final code review, lgtm, size:L

#5673 Issue 5664 - fix fonts not loading when switching between template parts
  src/extensions/text/fonts/loadFonts.js
Labels: bug 🐛, Final code review, lgtm, size:M

#5677 Update license.txt
  license.txt
Labels: ✍ documentation, lgtm, size:S

#5674 Issue 4786 - Enqueue Roboto on editor when maxi plugin is enabled
  core/admin/fonts/roboto/KFOmCnqEu92Fr1Mu4mxK.woff2
  core/admin/fonts/roboto/style.css
  core/class-maxi-core.php
Labels: 👩‍💻 pre-code testing, Final code review, lgtm, size:S

#5675 Issue 5671: current for specific post templates
  src/extensions/DC/getDCEntity.js
  src/extensions/DC/getTypes.js
  src/extensions/DC/utils.js
Labels: 🌟 enhancement, 🙏 need for library, Final code review, need for .org plugin directory, 🧑‍🚒 need for theme 🧑‍🚒, dynamic content, lgtm, size:L, 1.9.4
