Repository maxi-blocks/maxi-blocks, pull requests merged in 2024-03, with the labels that each got.

#5466 Fix Template Library insert for FSE - Templates - Pages
  src/editor/responsive-selector/index.js
Labels: bug 🐛, front testing, 🧑‍🚒 need for theme 🧑‍🚒, lgtm, size:XS, 1.7.3

#5465 CL / DC: current archive page
  core/class-maxi-dynamic-content.php
  core/class-maxi-styles.php
  src/components/context-loop/index.js
  src/components/dynamic-content/index.js
  src/extensions/DC/constants.js
  src/extensions/DC/getDCOptions.js
  src/extensions/DC/utils.js
Labels: 🌟 enhancement, Final code review, 🧑‍🚒 need for theme 🧑‍🚒, lgtm, size:L

#5459 Issue 5407 - author, tags, categories DC links rework
  core/blocks/class-maxi-block.php
  core/class-maxi-dynamic-content.php
  src/components/context-loop/index.js
  src/components/dynamic-content/index.js
  src/components/inspector-tabs/inspector-context-loop.js
  src/components/maxi-block/getMaxiBlockAttributes.js
  src/components/maxi-block/maxiBlock.js
  src/components/toolbar/components/link/index.js
  src/components/toolbar/index.js
  src/extensions/DC/constants.js
  src/extensions/DC/getDCContent.js
  src/extensions/DC/getDCLink.js
  src/extensions/DC/getWCContent.js
  src/extensions/DC/utils.js
  src/extensions/DC/validateDCAttributes.js
  src/extensions/DC/withMaxiDC.js
  src/extensions/save/utils.js
  src/extensions/styles/defaults/dynamicContent.js
  src/extensions/styles/migrators/blockMigrator.js
  src/extensions/styles/migrators/inlineDCLinkMigrator.js
Labels: 🌟 enhancement, Final code review, lgtm, size:L

#5469 Optimization: frontend scripts
  core/admin/class-maxi-dashboard.php
  core/class-maxi-core.php
  core/class-maxi-styles.php
Labels: 🌟 enhancement, optimization, seo optimization, Final code review, lgtm, size:S

#5474 Add a preview exception for our future theme patterns
  src/extensions/maxi-block/maxiBlockComponent.js
Labels: 🌟 enhancement, 🧑‍🚒 need for theme 🧑‍🚒, size:XS

#5471 Fix: current page font family for pagination
  src/extensions/style-cards/getSCStyles.js
  src/extensions/style-cards/test/__snapshots__/getSCStyles.js.snap
Labels: bug 🐛, Final code review, 🧑‍🚒 need for theme 🧑‍🚒, lgtm, size:XS, 1.7.3

#5475 Issue 5427 - fixed responsive bug
  src/components/relation-control/index.js
  src/extensions/maxi-block/cleanAttributes.js
  src/extensions/maxi-block/handleSetAttributes.js
  src/extensions/relations/getCleanResponseIBAttributes.js
  src/extensions/relations/updateRelationsRemotely.js
Labels: bug 🐛, Final code review, lgtm, size:S

#5468 Issue 5314: IB preview in FSE
  src/extensions/relations/Relation.js
Labels: 🌟 enhancement, 👩‍💻 pre-code testing, Final code review, 🧑‍🚒 need for theme 🧑‍🚒, lgtm, size:M, fse

#5484 Remove PR 5459 Issue 5407 - author, tags, categories DC links rework
  core/blocks/class-maxi-block.php
  core/class-maxi-dynamic-content.php
  src/components/context-loop/index.js
  src/components/dynamic-content/index.js
  src/components/inspector-tabs/inspector-context-loop.js
  src/components/maxi-block/getMaxiBlockAttributes.js
  src/components/maxi-block/maxiBlock.js
  src/components/toolbar/components/link/index.js
  src/extensions/DC/constants.js
  src/extensions/DC/getDCContent.js
  src/extensions/DC/getDCLink.js
  src/extensions/DC/getWCContent.js
  src/extensions/DC/utils.js
  src/extensions/DC/validateDCAttributes.js
  src/extensions/DC/withMaxiDC.js
  src/extensions/save/utils.js
  src/extensions/styles/defaults/dynamicContent.js
  src/extensions/styles/migrators/blockMigrator.js
  src/extensions/styles/migrators/inlineDCLinkMigrator.js
Labels: bug 🐛, 🙏 high priority, Final code review, 👀 *****fast track***** 👀, lgtm, size:L, 1.7.3

#5424 Issue 5079 - DC custom post type and custom taxonomies support
  core/class-maxi-dynamic-content.php
  src/components/context-loop/index.js
  src/components/dynamic-content/acf-settings-control/index.js
  src/components/dynamic-content/index.js
  src/extensions/DC/constants.js
  src/extensions/DC/getDCContent.js
  src/extensions/DC/getDCEntity.js
  src/extensions/DC/getDCOptions.js
  src/extensions/DC/getTypes.js
  src/extensions/DC/index.js
  src/extensions/DC/store/actions.js
  src/extensions/DC/store/controls.js
  src/extensions/DC/store/index.js
  src/extensions/DC/store/reducer.js
  src/extensions/DC/store/selectors.js
  src/extensions/DC/utils.js
  src/extensions/DC/withMaxiDC.js
  src/extensions/styles/defaults/contextLoop.js
  src/extensions/styles/defaults/dynamicContent.js
Labels: 🌟 enhancement, Final code review, lgtm, size:XL

#5480 1.7.3
  changelog.txt
  e2e-tests/blocks/Divider-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/Group-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/button-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/column-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/container-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/number-counter-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/row-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/svg-icon-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/text-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/video-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/components/background/__snapshots__/SVGIconBackground.spec.js.snap
  e2e-tests/components/icon-control/__snapshots__/index.spec.js.snap
  e2e-tests/components/repeater/__snapshots__/index.spec.js.snap
  e2e-tests/components/repeater/content.js
  e2e-tests/components/svg-color/__snapshots__/index.spec.js.snap
  e2e-tests/components/svg-stroke-width-control/__snapshots__/index.spec.js.snap
  e2e-tests/components/video-options-control/__snapshots__/index.spec.js.snap
  languages/maxi-blocks.pot
  plugin.php
  readme.txt
Labels: 🌟 enhancement, size:XL

#5490 Wp org: blocks section fix
  src/blocks/accordion-maxi/block.json
  src/blocks/button-maxi/block.json
  src/blocks/cloud-maxi/index.js
  src/blocks/column-maxi/block.json
  src/blocks/container-maxi/block.json
  src/blocks/divider-maxi/block.json
  src/blocks/group-maxi/block.json
  src/blocks/image-maxi/block.json
  src/blocks/list-item-maxi/block.json
  src/blocks/map-maxi/block.json
  src/blocks/number-counter-maxi/block.json
  src/blocks/pane-maxi/block.json
  src/blocks/row-maxi/block.json
  src/blocks/search-maxi/block.json
  src/blocks/slide-maxi/block.json
  src/blocks/slider-maxi/block.json
  src/blocks/svg-icon-maxi/block.json
  src/blocks/text-maxi/block.json
  src/blocks/video-maxi/block.json
Labels: bug 🐛, 🌟 enhancement, 🙏 high priority, Final code review, lgtm, size:M, 1.7.4

#5491 Issue 5402 - parse special characters
  src/extensions/DC/withMaxiDC.js
Labels: Final code review, lgtm

#5493 FSE patterns previews
  e2e-tests/blocks/column-maxi/index.spec.js
  src/extensions/maxi-block/maxiBlockComponent.js
Labels: 🌟 enhancement, Final code review, 🧑‍🚒 need for theme 🧑‍🚒, lgtm, size:L, 1.7.4

#5487 Add images as previews to Maxi Patterns in Gutenberg Block Inserter
  img/pattern-preview-edit.jpg
  src/components/popover/index.js
  src/css/editor.scss
  src/extensions/fse/getSiteEditorPreviewIframes.js
Labels: 🌟 enhancement, 🙏 high priority, Final code review, 🧑‍🚒 need for theme 🧑‍🚒, lgtm, size:S, 1.7.4

#5503 Fixes for WP 6.5 RC2
  core/class-maxi-api.php
  src/css/editor.scss
  src/editor/responsive-selector/index.js
  src/extensions/maxi-block/maxiBlockComponent.js
  src/extensions/store/actions.js
  src/extensions/store/reducer.js
Labels: Final code review, lgtm, size:L, 1.7.4

#5495 Issue 5248 - reusable blocks styles
  src/components/maxi-block/maxiBlock.js
  src/css/maxi-themes-banner.scss
  src/extensions/attributes/withAttributes.js
  src/extensions/maxi-block/maxiBlockComponent.js
  src/extensions/maxi-block/updateReusableBlockSize.js
Labels: 🌟 enhancement, 🙏 high priority, Final code review, 👀 *****fast track***** 👀, lgtm, size:M

#5507 Adds back current and current archive options
  src/extensions/DC/getDCOptions.js
  src/extensions/DC/utils.js
Labels: 🌟 enhancement, 🙏 high priority, Final code review, 🧑‍🚒 need for theme 🧑‍🚒, lgtm, size:M, 1.7.4

#5509 Issue 5502: block style from a template part inside a template
  src/extensions/attributes/withAttributes.js
Labels: bug 🐛, Final code review, lgtm, size:XS, 1.7.4

#5513 Issue 5512 - ensure text remains visible during webfont load
  core/class-maxi-local-fonts.php
  src/extensions/text/fonts/loadFonts.js
Labels: bug 🐛, Final code review, lgtm, size:XS

#5517 Issue 5515 blocks loosing styles in core blocks
  src/css/maxi-themes-banner.scss
  src/extensions/attributes/withAttributes.js
  src/extensions/styles/migrators/transitionMigrator.js
Labels: bug 🐛, Final code review, 🧑‍🚒 need for theme 🧑‍🚒, lgtm, size:M, 1.7.4

#5519 Update npm packages for speed and security
  package-lock.json
  package.json
Labels: ✍ documentation, 🙏 high priority, Final code review, 👀 *****fast track***** 👀, lgtm, size:L, 1.7.4, security

#5526 Update langchain packages
  package-lock.json
  package.json
  src/components/prompt-control/utils.js
Labels: bug 🐛, 🙏 high priority, front testing, lgtm, size:XS, 1.8.0, security

#5524 Fix "Specified key was too long; max key length is 1000 bytes" on some DB configurations
  core/class-maxi-db.php
Labels: bug 🐛, 🙏 high priority, Final code review, from support, lgtm, size:XS, 1.8.0

#5530 Fix styles on plugins page
  src/blocks/list-item-maxi/style.scss
  src/blocks/text-maxi/style.scss
Labels: bug 🐛, Final code review, lgtm, size:XS, 1.8.0
