Repository maxi-blocks/maxi-blocks, pull requests merged in 2024-10, with the labels that each got.

#5762 Backend optimization
  e2e-tests/blocks/Divider-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/Group-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/container-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/number-counter-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/video-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/editor/responsive.spec.js
  src/css/editor.scss
  src/editor/responsive-selector/index.js
  src/extensions/dom/dom.js
  src/extensions/maxi-block/maxiBlockComponent.js
  src/extensions/store/reducer.js
Labels: 🌟 enhancement, Final code review, lgtm, size:L, 1.9.9

#5759 Switch to GPLv3 or later
  README.md
  languages/maxi-blocks.pot
  license.txt
  plugin.php
  readme.txt
Labels: ✍ documentation, size:S, 1.9.9

#5763 1.9.9
  changelog.txt
  e2e-tests/blocks/Divider-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/Group-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/button-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/column-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/container-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/number-counter-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/row-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/svg-icon-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/text-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/video-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/components/background/__snapshots__/SVGIconBackground.spec.js.snap
  e2e-tests/components/icon-control/__snapshots__/index.spec.js.snap
  e2e-tests/components/repeater/__snapshots__/index.spec.js.snap
  e2e-tests/components/repeater/content.js
  e2e-tests/components/svg-color/__snapshots__/index.spec.js.snap
  e2e-tests/components/svg-stroke-width-control/__snapshots__/index.spec.js.snap
  e2e-tests/components/video-options-control/__snapshots__/index.spec.js.snap
  languages/maxi-blocks.pot
  plugin.php
  readme.txt
Labels: size:M

#5765 Backend optimization 2
  e2e-tests/components/flex-settings-control/__snapshots__/index.spec.js.snap
  src/extensions/maxi-block/maxiBlockComponent.js
  src/extensions/styles/helpers/getButtonIconStyles.js
  src/extensions/styles/helpers/getIconPathStyles.js
  src/extensions/styles/helpers/getIconStyles.js
  src/extensions/styles/helpers/getSVGStyles.js
  src/extensions/svg/getSVGAspectRatio.js
  src/extensions/svg/getSVGPosition.js
  src/extensions/svg/getSVGWidthHeightRatio.js
Labels: optimization, Final code review, lgtm, size:XL, 2.0.0

#5721 Issue 5706 - fix reset for DC values
  src/components/context-loop/index.js
  src/components/dynamic-content/index.js
Labels: bug 🐛, Final code review, lgtm, size:S

#5768 Backend optimization 3
  src/components/context-loop/index.js
  src/extensions/DC/getDCContent.js
  src/extensions/DC/getDCEntity.js
  src/extensions/DC/getDCLink.js
  src/extensions/DC/getDCMedia.js
  src/extensions/DC/getDCOptions.js
  src/extensions/DC/getDCValues.js
Labels: Final code review, lgtm, size:L, 2.0.0

#5769 2.0.0
  changelog.txt
  core/class-maxi-style-cards.php
  core/class-maxi-styles.php
  core/defaults/sc_defaults.php
  e2e-tests/blocks/Divider-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/Group-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/button-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/column-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/container-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/number-counter-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/row-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/svg-icon-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/text-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/video-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/components/background/__snapshots__/SVGIconBackground.spec.js.snap
  e2e-tests/components/icon-control/__snapshots__/index.spec.js.snap
  e2e-tests/components/repeater/__snapshots__/index.spec.js.snap
  e2e-tests/components/repeater/content.js
  e2e-tests/components/svg-color/__snapshots__/index.spec.js.snap
  e2e-tests/components/svg-stroke-width-control/__snapshots__/index.spec.js.snap
  e2e-tests/components/video-options-control/__snapshots__/index.spec.js.snap
  js/maxi-relations.js
  languages/maxi-blocks.pot
  plugin.php
  readme.txt
  src/editor/library/utils/onRequestInsertPattern.js
Labels: size:L

#5779 Issue 5776: responsive for old blocks
  core/class-maxi-styles.php
  src/extensions/maxi-block/compareVersions.js
  src/extensions/maxi-block/maxiBlockComponent.js
  src/extensions/styles/helpers/getMarginPaddingStyles.js
Labels: Final code review, lgtm, size:L, 2.0.1

#5789 Issue 5784: SC link and button bg colours
  core/defaults/defaultSC.json
  e2e-tests/editor/__snapshots__/sc-variable.spec.js.snap
  e2e-tests/editor/style-cards/__snapshots__/button.spec.js.snap
  src/editor/library/container.js
  src/extensions/style-cards/test/__snapshots__/getSCStyles.js.snap
  src/extensions/style-cards/test/__snapshots__/getSCVariablesObject.js.snap
  src/extensions/style-cards/test/__snapshots__/updateSCOnEditor.js.snap
Labels: Final code review, lgtm, size:S, 2.0.1

#5788 Issue 5778: Fix xxl styles on breakpoint switch
  e2e-tests/components/toolbar/components/text-color/index.spec.js
  src/extensions/maxi-block/maxiBlockComponent.js
Labels: bug 🐛, Final code review, lgtm, size:S, 2.0.1

#5773 Text split fix / new default blocks
  e2e-tests/components/block-resizer/index.spec.js
  e2e-tests/components/icon/index.spec.js
  e2e-tests/components/repeater/index.spec.js
  e2e-tests/components/toolbar/components/delete/index.spec.js
  src/blocks/text-maxi/block.json
  src/components/block-inserter/editor.scss
  src/components/maxi-block/maxiBlock.js
  src/css/editor.scss
  src/extensions/dom/dom.js
  src/extensions/maxi-block/maxiBlockComponent.js
  src/extensions/maxi-block/withMaxiProps.js
Labels: 🌟 enhancement, Final code review, lgtm, size:L, enhancement, 2.0.1

#5794 Fix fonts with spaces in names on backend
  core/class-maxi-api.php
  e2e-tests/components/font-family-selector/index.spec.js
  fonts/fonts.json
  src/extensions/text/store/resolvers.js
Labels: bug 🐛, front testing, from support, lgtm, size:M, 2.0.1
