Repository maxi-blocks/maxi-blocks, pull requests merged in 2024-04, with the labels that each got.

#5533 Issue 5532 fonts
  core/class-maxi-styles.php
  src/extensions/maxi-block/maxiBlockComponent.js
  src/extensions/text/fonts/loadFonts.js
  src/extensions/text/fonts/utils.js
Labels: bug 🐛, Final code review, from support, lgtm, size:M, 1.8.0

#5534 1.8.0
  changelog.txt
  e2e-tests/blocks/Divider-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/Group-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/button-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/column-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/container-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/number-counter-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/row-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/svg-icon-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/text-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/video-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/components/background/__snapshots__/SVGIconBackground.spec.js.snap
  e2e-tests/components/icon-control/__snapshots__/index.spec.js.snap
  e2e-tests/components/repeater/__snapshots__/index.spec.js.snap
  e2e-tests/components/repeater/content.js
  e2e-tests/components/svg-color/__snapshots__/index.spec.js.snap
  e2e-tests/components/svg-stroke-width-control/__snapshots__/index.spec.js.snap
  e2e-tests/components/video-options-control/__snapshots__/index.spec.js.snap
  languages/maxi-blocks.pot
  plugin.php
  readme.txt
Labels: ✍ documentation, size:M

#5537 1.8.1
  changelog.txt
  e2e-tests/blocks/Divider-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/Group-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/button-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/column-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/container-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/number-counter-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/row-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/svg-icon-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/text-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/video-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/components/background/__snapshots__/SVGIconBackground.spec.js.snap
  e2e-tests/components/icon-control/__snapshots__/index.spec.js.snap
  e2e-tests/components/repeater/__snapshots__/index.spec.js.snap
  e2e-tests/components/repeater/content.js
  e2e-tests/components/svg-color/__snapshots__/index.spec.js.snap
  e2e-tests/components/svg-stroke-width-control/__snapshots__/index.spec.js.snap
  e2e-tests/components/video-options-control/__snapshots__/index.spec.js.snap
  plugin.php
  readme.txt
  src/extensions/styles/migrators/listItemMigrator.js
Labels: bug 🐛, ✍ documentation, size:S

#5528 Issue 5510: get current
  core/class-maxi-dynamic-content.php
  src/components/context-loop/index.js
  src/components/dynamic-content/index.js
  src/components/link-control/editor.scss
  src/extensions/DC/constants.js
  src/extensions/DC/getDCContent.js
  src/extensions/DC/getDCEntity.js
  src/extensions/DC/getDCOptions.js
  src/extensions/DC/getTypes.js
  src/extensions/DC/utils.js
Labels: 🌟 enhancement, 🙏 high priority, Final code review, 🧑‍🚒 need for theme 🧑‍🚒, lgtm, size:XL, 1.8.2

#5536 Prevent infinite 'IB effects' migration
  src/extensions/styles/migrators/IBEffectsMigrator.js
Labels: Final code review, lgtm, size:XS, 1.8.2

#5539 Fix looping Transition migrator
  src/extensions/styles/migrators/transitionMigrator.js
Labels: bug 🐛, 🧑‍🚒 need for theme 🧑‍🚒, lgtm, size:XS, 1.8.3

#5540 Fix DC links BG and other styles
  core/class-maxi-dynamic-content.php
  src/blocks/text-maxi/styles.js
  src/components/dynamic-content/index.js
  src/extensions/DC/getTypes.js
Labels: bug 🐛, Final code review, 👀 *****fast track***** 👀, 🧑‍🚒 need for theme 🧑‍🚒, lgtm, size:M, 1.8.2

#5541 1.8.2
  changelog.txt
  e2e-tests/blocks/Divider-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/Group-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/button-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/column-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/container-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/number-counter-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/row-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/svg-icon-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/text-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/video-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/components/background/__snapshots__/SVGIconBackground.spec.js.snap
  e2e-tests/components/icon-control/__snapshots__/index.spec.js.snap
  e2e-tests/components/repeater/__snapshots__/index.spec.js.snap
  e2e-tests/components/repeater/content.js
  e2e-tests/components/svg-color/__snapshots__/index.spec.js.snap
  e2e-tests/components/svg-stroke-width-control/__snapshots__/index.spec.js.snap
  e2e-tests/components/video-options-control/__snapshots__/index.spec.js.snap
  languages/maxi-blocks.pot
  plugin.php
  readme.txt
Labels: ✍ documentation, size:L

#5548 Issue 5546: transition in ff
  js/maxi-relations.js
Labels: bug 🐛, Final code review, from support, lgtm, size:XS, 1.8.3

#5547 Issue 5543: for theme
  src/extensions/style-cards/getSCStyles.js
  src/extensions/style-cards/test/__snapshots__/getSCStyles.js.snap
Labels: Final code review, lgtm, size:M

#5550 Issue with broken custom css on save
  core/class-maxi-dynamic-content.php
  src/extensions/styles/store/controls.js
Labels: Final code review, lgtm, size:M, 1.8.3

#5552 Issue 5551: for theme
  core/class-maxi-dynamic-content.php
  core/defaults/defaultSC.json
  src/css/maxi-themes-banner.scss
  src/extensions/style-cards/getSCStyles.js
  src/extensions/style-cards/test/__snapshots__/getSCStyles.js.snap
Labels: bug 🐛, 🙏 high priority, 👩‍💻 pre-code testing, 🧑‍🚒 need for theme 🧑‍🚒, lgtm, size:M, 1.8.3

#5553 Styles for beta theme
  core/class-maxi-styles.php
Labels: 🌟 enhancement, 🙏 high priority, Final code review, lgtm, size:L, 1.8.3

#5560 Fix ACF image not loading on frontend
  core/blocks/class-maxi-block.php
  core/class-maxi-api.php
  core/class-maxi-dynamic-content.php
  src/extensions/DC/getDCMedia.js
Labels: bug 🐛, Final code review, from support, lgtm, size:L

#5569 Fix styles for native blocks that are not inside maxi blocks
  src/css/maxi-themes-banner.scss
Labels: bug 🐛, Final code review, lgtm, size:XS, 1.8.4

#5573 For beta theme - round 3
  src/css/maxi-themes-banner.scss
  src/extensions/maxi-block/maxiBlockComponent.js
  src/extensions/styles/migrators/SVGTransitionMigrator.js
Labels: bug 🐛, Final code review, 🧑‍🚒 need for theme 🧑‍🚒, lgtm, size:M, 1.8.4
