Repository maxi-blocks/maxi-blocks, pull requests merged in 2024-02, with the labels that each got.

#5415 Issue 5410 - Fix link change in lists
  e2e-tests/blocks/text-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/text-maxi/index.spec.js
  package-lock.json
  package.json
  src/blocks/text-maxi/edit.js
  src/blocks/text-maxi/index.js
  src/extensions/styles/migrators/index.js
  src/extensions/styles/migrators/listBrMigrator.js
  src/extensions/text/formats/onChangeRichText.js
  src/extensions/text/formats/setFormat.js
Labels: Final code review, lgtm, size:L

#5418 PHP warnings fix
  core/class-maxi-dynamic-content.php
  core/class-maxi-styles.php
Labels: bug 🐛, Final code review, lgtm, size:S

#5419 1.6.1
  .wp-env.json
  changelog.txt
  e2e-tests/blocks/Divider-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/Group-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/button-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/column-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/container-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/number-counter-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/row-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/svg-icon-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/text-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/video-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/components/background/__snapshots__/SVGIconBackground.spec.js.snap
  e2e-tests/components/icon-control/__snapshots__/index.spec.js.snap
  e2e-tests/components/repeater/__snapshots__/index.spec.js.snap
  e2e-tests/components/repeater/content.js
  e2e-tests/components/svg-color/__snapshots__/index.spec.js.snap
  e2e-tests/components/svg-stroke-width-control/__snapshots__/index.spec.js.snap
  e2e-tests/components/video-options-control/__snapshots__/index.spec.js.snap
  languages/maxi-blocks.pot
  plugin.php
  readme.txt
Labels: ✍ documentation, size:L

#5414 Navigation menus
  core/class-maxi-style-cards.php
  core/class-maxi-styles.php
  core/defaults/defaultSC.json
  e2e-tests/editor/__snapshots__/sc-variable.spec.js.snap
  js/maxi-navigation.js
  src/blocks/container-maxi/edit.js
  src/blocks/container-maxi/editor.scss
  src/css/style.scss
  src/editor/style-cards/maxiStyleCardsTab.js
  src/editor/style-cards/utils.js
  src/editor/toolbar-buttons/editor.scss
  src/extensions/dom/dom.js
  src/extensions/style-cards/getSCStyles.js
  src/extensions/style-cards/getSCVariablesObject.js
  src/extensions/style-cards/store/selectors.js
  src/extensions/style-cards/test/__snapshots__/getSCStyles.js.snap
  src/extensions/style-cards/test/__snapshots__/getSCVariablesObject.js.snap
  src/extensions/style-cards/test/__snapshots__/updateSCOnEditor.js.snap
Labels: 🌟 enhancement, 👩‍💻 pre-code testing, Final code review, ⛏ ++ needs deep testing ++ ⛏, 🧑‍🚒 need for theme 🧑‍🚒, lgtm, size:XXL

#5421 Navigation Block: Add background option for mobile navigation
  core/defaults/defaultSC.json
  src/editor/style-cards/maxiStyleCardsTab.js
  src/extensions/style-cards/getSCStyles.js
  src/extensions/style-cards/getSCVariablesObject.js
  src/extensions/style-cards/store/selectors.js
  src/extensions/style-cards/test/__snapshots__/getSCStyles.js.snap
Labels: 🌟 enhancement, Final code review, 👀 *****fast track***** 👀, lgtm, size:M, 1.7.0

#5426 Fix: colour opacity
  core/class-maxi-styles.php
Labels: Final code review, lgtm, size:XS

#5438 Issue 5429 - SC: set s breakpoint max-width to 767 on frontend
  src/extensions/style-cards/getSCStyles.js
  src/extensions/style-cards/test/__snapshots__/getSCStyles.js.snap
Labels: bug 🐛, Final code review, lgtm, size:XS

#5413 Issue 5328 - Scroll effects update: custom zones & units
  .vscode/settings.json
  js/maxi-scroll-effects.js
  package-lock.json
  package.json
  src/components/maxi-block/getMaxiBlockAttributes.js
  src/components/maxi-block/getOldScrollAttributes.js
  src/components/scroll-effects-control/editor.scss
  src/components/scroll-effects-control/effect-properties.js
  src/components/scroll-effects-control/index.js
  src/components/scroll-effects-control/options.js
  src/components/scroll-effects-control/scroll-effect-unique-control.js
  src/components/scroll-effects-control/shortcuts.js
  src/extensions/copy-paste/test/__snapshots__/copy-paste.js.snap
  src/extensions/maxi-block/maxiBlockComponent.js
  src/extensions/styles/defaults/scroll.js
  src/extensions/styles/migrators/blockMigrator.js
  src/extensions/styles/migrators/scrollEffectsMigrator.js
  src/extensions/styles/utils.js
Labels: Final code review, lgtm, size:XXL

#5434 Issue 5427 - fix conflict between IB and responsive
  src/extensions/maxi-block/cleanAttributes.js
  src/extensions/maxi-block/test/cleanAttributes.js
  src/extensions/maxi-block/test/handleSetAttributes.js
  src/extensions/styles/store/actions.js
  src/extensions/styles/store/reducer.js
  src/extensions/styles/store/selectors.js
Labels: bug 🐛, Final code review, lgtm, size:L

#5447 Issue 5442 - Scroll effects: add element null checks on frontend
  js/maxi-scroll-effects.js
Labels: bug 🐛, Final code review, lgtm, size:XS

#5441 Optimization
  core/class-maxi-api.php
  core/class-maxi-dynamic-content.php
  languages/maxi-blocks.pot
  package-lock.json
  package.json
  src/blocks/accordion-maxi/block.json
  src/blocks/button-maxi/block.json
  src/blocks/button-maxi/edit.js
  src/blocks/button-maxi/inspector.js
  src/blocks/column-maxi/block.json
  src/blocks/container-maxi/block.json
  src/blocks/divider-maxi/block.json
  src/blocks/group-maxi/block.json
  src/blocks/image-maxi/block.json
  src/blocks/image-maxi/components/dimension-tab/index.js
  src/blocks/image-maxi/components/hover-effect-control/index.js
  src/blocks/image-maxi/edit.js
  src/blocks/map-maxi/block.json
  src/blocks/map-maxi/components/map-content/index.js
  src/blocks/map-maxi/components/markers/index.js
  src/blocks/number-counter-maxi/block.json
  src/blocks/pane-maxi/block.json
  src/blocks/row-maxi/block.json
  src/blocks/search-maxi/block.json
  src/blocks/slide-maxi/block.json
  src/blocks/slider-maxi/block.json
  src/blocks/slider-maxi/edit.js
  src/blocks/svg-icon-maxi/block.json
  src/blocks/text-maxi/block.json
  src/blocks/text-maxi/components/list-options-control/index.js
  src/blocks/video-maxi/block.json
  src/blocks/video-maxi/save.js
  src/components/accordion-control/Accordion.js
  src/components/content-loader/img/1.svg
  src/components/content-loader/img/2.svg
  src/components/content-loader/img/3.svg
  src/components/content-loader/img/4.svg
  src/components/content-loader/img/5.svg
  src/components/content-loader/img/6.svg
  src/components/content-loader/index.js
  src/components/css-code-editor/index.js
  src/extensions/styles/helpers/getDividerStyles.js
  src/extensions/text/formats/flatFormatsWithClass.js
  src/extensions/text/formats/removeCustomFormat.js
  src/extensions/text/formats/removeLinkFormat.js
  src/extensions/text/formats/setCustomFormatsWhenPaste.js
  src/extensions/text/formats/updateCustomFormatStyle.js
  webpack.config.js
Labels: bug 🐛, Final code review, lgtm, size:XXL

#5453 1.7.1
  .wp-env.json
  changelog.txt
  e2e-tests/blocks/Divider-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/Group-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/button-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/column-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/container-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/number-counter-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/row-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/svg-icon-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/text-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/video-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/components/background/__snapshots__/SVGIconBackground.spec.js.snap
  e2e-tests/components/icon-control/__snapshots__/index.spec.js.snap
  e2e-tests/components/repeater/__snapshots__/index.spec.js.snap
  e2e-tests/components/repeater/content.js
  e2e-tests/components/svg-color/__snapshots__/index.spec.js.snap
  e2e-tests/components/svg-stroke-width-control/__snapshots__/index.spec.js.snap
  e2e-tests/components/video-options-control/__snapshots__/index.spec.js.snap
  languages/maxi-blocks.pot
  package-lock.json
  package.json
  plugin.php
  readme.txt
Labels: 🌟 enhancement, size:M

#5456 Add Update notification
  core/admin/class-maxi-dashboard.php
  core/admin/notices.js
  core/class-maxi-blocks.php
  core/class-maxi-core.php
  core/class-maxi-styles.php
  plugin.php
Labels: 🌟 enhancement, 🙏 high priority, 👩‍💻 pre-code testing, Final code review, 👀 *****fast track***** 👀, lgtm, size:M, 1.7.2

#5458 1.7.2
  changelog.txt
  e2e-tests/blocks/Divider-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/Group-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/button-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/column-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/container-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/number-counter-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/row-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/svg-icon-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/text-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/video-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/components/background/__snapshots__/SVGIconBackground.spec.js.snap
  e2e-tests/components/icon-control/__snapshots__/index.spec.js.snap
  e2e-tests/components/repeater/__snapshots__/index.spec.js.snap
  e2e-tests/components/repeater/content.js
  e2e-tests/components/svg-color/__snapshots__/index.spec.js.snap
  e2e-tests/components/svg-stroke-width-control/__snapshots__/index.spec.js.snap
  e2e-tests/components/video-options-control/__snapshots__/index.spec.js.snap
  languages/maxi-blocks.pot
  plugin.php
  readme.txt
Labels: 🌟 enhancement, size:L

#5428 Pagination for CL
  core/blocks/class-maxi-block.php
  core/blocks/utils/default-group-attributes.json
  core/blocks/utils/defaults/contextLoop.json
  core/class-maxi-api.php
  core/class-maxi-dynamic-content.php
  core/class-maxi-styles.php
  src/blocks/column-maxi/styles.js
  src/blocks/container-maxi/attributes.js
  src/blocks/container-maxi/edit.js
  src/blocks/container-maxi/styles.js
  src/blocks/group-maxi/styles.js
  src/blocks/row-maxi/styles.js
  src/components/context-loop/index.js
  src/components/flex-settings-control/flex-align-control.js
  src/components/flex-settings-control/flex-content-align-control.js
  src/components/flex-settings-control/flex-direction-control.js
  src/components/flex-settings-control/flex-gap-control.js
  src/components/flex-settings-control/flex-wrap-control.js
  src/components/flex-settings-control/index.js
  src/components/inspector-tabs/inspector-context-loop.js
  src/components/link-control/index.js
  src/components/maxi-block/innerBlocksBlock.js
  src/components/maxi-block/maxiBlock.js
  src/components/maxi-block/pagination.js
  src/components/toolbar/components/context-loop/index.js
  src/components/toolbar/index.js
  src/css/style.scss
  src/extensions/DC/constants.js
  src/extensions/maxi-block/maxiBlockComponent.js
  src/extensions/style-cards/getSCStyles.js
  src/extensions/style-cards/test/__snapshots__/getSCStyles.js.snap
  src/extensions/styles/defaults/contextLoop.js
  src/extensions/styles/helpers/getFlexStyles.js
  src/extensions/styles/helpers/getPaginationStyles.js
  src/extensions/styles/helpers/index.js
  src/extensions/text/fonts/utils.js
Labels: 🌟 enhancement, components, 🙏 high priority, 💪 hard, 🙏 need for library, 👩‍💻 pre-code testing, Final code review, 🧑‍🚒 need for theme 🧑‍🚒, context loop, lgtm, size:XXL, 1.7.2

#5454 Fix search link
  core/class-maxi-styles.php
  js/maxi-search.js
Labels: bug 🐛, Final code review, lgtm, size:S

#5460 Issue 5455: FSE image preview
  img/pattern-preview.jpg
  src/css/editor.scss
  src/extensions/dom/dom.js
  src/extensions/fse/getSiteEditorPreviewIframesBodies.js
  src/extensions/fse/index.js
  src/extensions/maxi-block/maxiBlockComponent.js
  src/extensions/style-cards/updateSCOnEditor.js
Labels: 🌟 enhancement, 🙏 high priority, 👩‍💻 pre-code testing, Final code review, 🧑‍🚒 need for theme 🧑‍🚒, lgtm, size:L, 1.7.3

#5462 Wp directory fixes
  languages/maxi-blocks.pot
  package-lock.json
  package.json
  src/components/dynamic-content/custom-date-formatting/index.js
  src/extensions/DC/processDCDate.js
  src/extensions/DC/utils.js
  src/extensions/DC/withMaxiDC.js
Labels: bug 🐛, 🌟 enhancement, 🙏 high priority, Final code review, lgtm, size:L, 1.7.3
