Repository maxi-blocks/maxi-blocks, pull requests merged in 2024-12, with the labels that each got.

#5816 Issue 5235 - hide popovers that are causing horizontal scrollbar
  src/components/block-inserter/index.js
  src/components/popover/index.js
Labels: bug 🐛, Final code review, lgtm, size:M

#5820 Issue 5813 - Show "Switch tone" button for themes in library
  src/editor/library/container.js
  src/editor/library/toolbar.js
Labels: Final code review, lgtm, size:S

#5822 Issue 5619 - fix different max allowed values for toolbar and inspector
  src/components/toolbar/components/text-options/index.js
  src/components/typography-control/index.js
Labels: bug 🐛, Final code review, lgtm, size:M

#5821 Issue 5702 - update pagination items per page with column count
  src/components/context-loop/index.js
Labels: 🌟 enhancement, Final code review, lgtm, size:S

#5828 Issue 5824: fix image upload on slow servers
  src/editor/library/utils/imageUploader.js
Labels: bug 🐛, Final code review, lgtm, size:S

#5707 Issue 5351 - author DC improvements
  core/class-maxi-dynamic-content.php
  core/class-maxi-styles.php
  js/maxi-email-obfuscate.js
  src/components/context-loop/index.js
  src/components/dynamic-content/index.js
  src/components/link-control/index.js
  src/components/toggle-switch/editor.scss
  src/components/toggle-switch/index.js
  src/components/toolbar/components/link/editor.scss
  src/components/toolbar/components/link/index.js
  src/extensions/DC/constants.js
  src/extensions/DC/getDCContent.js
  src/extensions/DC/getDCEntity.js
  src/extensions/DC/getDCLink.js
  src/extensions/DC/getDCOptions.js
  src/extensions/DC/store/resolvers.js
  src/extensions/DC/utils.js
  src/extensions/maxi-block/maxiBlockComponent.js
  src/extensions/save/utils.js
  src/extensions/styles/defaults/dynamicContent.js
  src/extensions/text/lists/getLastChildIndex.js
  src/extensions/text/lists/indentListItems.js
  src/extensions/text/lists/outdentListItems.js
  src/extensions/text/lists/toTree.js
Labels: 🌟 enhancement, Final code review, lgtm, size:XL

#5832 2.0.5
  .github/workflows/e2e-test.yml
  .github/workflows/update-staging-maximaster.yml
  changelog.txt
  e2e-tests/blocks/Divider-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/Group-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/button-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/column-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/container-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/number-counter-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/row-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/svg-icon-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/text-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/video-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/components/background/__snapshots__/SVGIconBackground.spec.js.snap
  e2e-tests/components/icon-control/__snapshots__/index.spec.js.snap
  e2e-tests/components/repeater/__snapshots__/index.spec.js.snap
  e2e-tests/components/repeater/content.js
  e2e-tests/components/svg-color/__snapshots__/index.spec.js.snap
  e2e-tests/components/svg-stroke-width-control/__snapshots__/index.spec.js.snap
  e2e-tests/components/video-options-control/__snapshots__/index.spec.js.snap
  languages/maxi-blocks.pot
  plugin.php
  readme.txt
  src/editor/library/container.js
Labels: size:XXL

#5840 2.0.6
  changelog.txt
  core/class-maxi-dynamic-content.php
  e2e-tests/blocks/Divider-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/Group-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/button-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/column-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/container-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/number-counter-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/row-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/svg-icon-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/text-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/video-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/components/background/__snapshots__/SVGIconBackground.spec.js.snap
  e2e-tests/components/icon-control/__snapshots__/index.spec.js.snap
  e2e-tests/components/repeater/__snapshots__/index.spec.js.snap
  e2e-tests/components/repeater/content.js
  e2e-tests/components/svg-color/__snapshots__/index.spec.js.snap
  e2e-tests/components/svg-stroke-width-control/__snapshots__/index.spec.js.snap
  e2e-tests/components/video-options-control/__snapshots__/index.spec.js.snap
  languages/maxi-blocks.pot
  plugin.php
  readme.txt
  src/extensions/DC/fetchAndUpdateDCData.js
Labels: size:L

#5833 Issue 4678 - Add missing style helpers unit tests
  src/editor/library/container.js
  src/extensions/DC/getDCEntity.js
  src/extensions/style-cards/test/updateSCOnEditor.js
  src/extensions/styles/helpers/getIconPathStyles.js
  src/extensions/styles/helpers/getIconStyles.js
  src/extensions/styles/helpers/test/__snapshots__/getButtonIconStyles.js.snap
  src/extensions/styles/helpers/test/__snapshots__/getPaginationStyles.js.snap
  src/extensions/styles/helpers/test/getButtonIconStyles.js
  src/extensions/styles/helpers/test/getCustomCss.js
  src/extensions/styles/helpers/test/getFlexStyles.js
  src/extensions/styles/helpers/test/getIconPathStyles.js
  src/extensions/styles/helpers/test/getIconStyles.js
  src/extensions/styles/helpers/test/getImgWidthStyles.js
  src/extensions/styles/helpers/test/getPaginationStyles.js
  src/extensions/styles/helpers/test/getShapeStyles.js
  src/extensions/styles/test/styleProcessor.js
  src/extensions/text/formats/test/flatFormatsWithClass.js
  src/extensions/text/formats/test/getCustomFormatValue.js
  src/extensions/text/formats/test/setFormatWithClass.js
Labels: Final code review, lgtm, size:XXL

#5837 Issue 4217 - Create a hook to remove code duplication in placeholders
  src/editor/library/hooks.js
  src/editor/library/modal.js
Labels: Final code review, lgtm, size:M
