Repository maxi-blocks/maxi-blocks, pull requests merged in 2024-08, with the labels that each got.

#5685 1 9 4 master
  core/class-maxi-blocks.php
  core/class-maxi-dynamic-content.php
  core/class-maxi-styles.php
  e2e-tests/blocks/Divider-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/Group-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/button-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/column-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/container-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/number-counter-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/row-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/svg-icon-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/text-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/video-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/components/background/__snapshots__/SVGIconBackground.spec.js.snap
  e2e-tests/components/icon-control/__snapshots__/index.spec.js.snap
  e2e-tests/components/repeater/__snapshots__/index.spec.js.snap
  e2e-tests/components/repeater/content.js
  e2e-tests/components/svg-color/__snapshots__/index.spec.js.snap
  e2e-tests/components/svg-stroke-width-control/__snapshots__/index.spec.js.snap
  e2e-tests/components/video-options-control/__snapshots__/index.spec.js.snap
  languages/maxi-blocks.pot
  package-lock.json
  package.json
  plugin.php
  src/css/maxi-themes-banner.scss
  src/extensions/DC/getDCEntity.js
  src/extensions/DC/utils.js
  src/extensions/maxi-block/maxiBlockComponent.js
Labels: size:XXL

#5684 Issue 5680 - fix IB styles for icons
  e2e-tests/components/relation-control/__snapshots__/button-maxi.spec.js.snap
  js/maxi-relations.js
Labels: bug 🐛, Final code review, lgtm, size:S

#5695 Fix sc font
  core/class-maxi-styles.php
  src/extensions/text/fonts/utils.js
Labels: bug 🐛, 🙏 high priority, Final code review, lgtm, size:M, 1.9.5

#5690 Issue 5659 - add slider to set avatar size
  core/blocks/class-maxi-block.php
  core/class-maxi-dynamic-content.php
  src/components/dynamic-content/index.js
  src/extensions/DC/getDCMedia.js
  src/extensions/styles/defaults/dynamicContent.js
Labels: 🌟 enhancement, Final code review, lgtm, size:M

#5686 Backend speed
  core/admin/admin.js
  core/admin/class-maxi-dashboard.php
  fonts/fonts.json
  package-lock.json
  package.json
  src/blocks/accordion-maxi/edit.js
  src/blocks/button-maxi/edit.js
  src/blocks/button-maxi/utils.js
  src/blocks/column-maxi/edit.js
  src/blocks/container-maxi/edit.js
  src/blocks/group-maxi/edit.js
  src/blocks/image-maxi/edit.js
  src/blocks/map-maxi/edit.js
  src/blocks/row-maxi/components/column-pattern/index.js
  src/blocks/row-maxi/edit.js
  src/blocks/row-maxi/inspector.js
  src/blocks/search-maxi/edit.js
  src/blocks/svg-icon-maxi/edit.js
  src/blocks/video-maxi/edit.js
  src/components/block-inserter/editor.scss
  src/components/block-inserter/index.js
  src/components/toolbar/index.js
  src/editor/library/container.js
  src/editor/library/editor.scss
  src/editor/toolbar-buttons/index.js
  src/extensions/DC/fetchAndUpdateDCData.js
  src/extensions/DC/getDCContent.js
  src/extensions/DC/getDCEntity.js
  src/extensions/DC/getDCLink.js
  src/extensions/DC/getDCMedia.js
  src/extensions/DC/withMaxiContextLoop.js
  src/extensions/DC/withMaxiContextLoopContext.js
  src/extensions/DC/withMaxiDC.js
  src/extensions/attributes/withAttributes.js
  src/extensions/inspector/withMaxiInspector.js
  src/extensions/maxi-block/withMaxiLoader.js
  src/extensions/maxi-block/withMaxiProps.js
  src/extensions/styles/utils.js
  src/extensions/text/fonts/fonts.js
  src/extensions/text/store/actions.js
  src/extensions/text/store/index.js
  src/extensions/text/store/reducer.js
Labels: front testing, 👩‍💻 pre-code testing, Final code review, lgtm, size:XL, 1.9.5

#5700 Fix pagination font on backend
  src/extensions/maxi-block/maxiBlockComponent.js
Labels: bug 🐛, Final code review, lgtm, size:M

#5708 Eslint downgrade
  .babelrc.js
  .github/workflows/unit-test.yml
  .prettierignore
  package-lock.json
  package.json
  src/blocks/column-maxi/edit.js
  src/blocks/column-maxi/editor.scss
  src/blocks/svg-icon-maxi/edit.js
  src/blocks/svg-icon-maxi/editor.scss
  src/components/block-indicators/editor.scss
  src/components/prompt-control/components/result-modify-bar/editor.scss
  src/components/prompt-control/editor.scss
  src/components/toolbar/components/background-color/editor.scss
  src/components/toolbar/components/link/index.js
  src/components/toolbar/components/mover/editor.scss
  src/components/toolbar/components/text-margin/editor.scss
  src/components/toolbar/components/vertical-align/editor.scss
  src/components/toolbar/index.js
  src/extensions/DC/fetchAndUpdateDCData.js
  src/extensions/DC/getDCContent.js
  src/extensions/DC/getDCEntity.js
  src/extensions/DC/getTypes.js
  src/extensions/DC/utils.js
  src/extensions/DC/withMaxiDC.js
  src/extensions/fse/getSiteEditorIframe.js
  src/extensions/inspector/withMaxiInspector.js
  src/extensions/maxi-block/maxiBlockComponent.js
  src/extensions/relations/Relation.js
  src/extensions/store/reducer.js
  src/extensions/text/store/actions.js
Labels: size:XL

#5693 Performance tests
  .github/workflows/performance-test.yml
  e2e-tests/jest.config.e2e.js
  e2e-tests/jest.config.performance.js
  e2e-tests/performance-tests/blocks.perf.js
  e2e-tests/performance-tests/compare/argument-parser.js
  e2e-tests/performance-tests/compare/comparator.js
  e2e-tests/performance-tests/compare/compare.js
  e2e-tests/performance-tests/compare/result-writer.js
  e2e-tests/performance-tests/config.js
  e2e-tests/performance-tests/patterns.perf.js
  e2e-tests/performance-tests/utils.js
  e2e-tests/setup-test-framework.js
  package-lock.json
  package.json
  src/extensions/text/fonts/loadFonts.js
Labels: size:XXL
