Repository maxi-blocks/maxi-blocks, pull requests merged in 2024-11, with the labels that each got.

#5795 2.0.1
  changelog.txt
  core/class-maxi-styles.php
  e2e-tests/blocks/Divider-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/Group-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/button-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/column-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/container-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/number-counter-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/row-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/svg-icon-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/text-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/video-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/components/background/__snapshots__/SVGIconBackground.spec.js.snap
  e2e-tests/components/icon-control/__snapshots__/index.spec.js.snap
  e2e-tests/components/repeater/__snapshots__/index.spec.js.snap
  e2e-tests/components/repeater/content.js
  e2e-tests/components/svg-color/__snapshots__/index.spec.js.snap
  e2e-tests/components/svg-stroke-width-control/__snapshots__/index.spec.js.snap
  e2e-tests/components/video-options-control/__snapshots__/index.spec.js.snap
  languages/maxi-blocks.pot
  plugin.php
  readme.txt
  src/components/block-inserter/editor.scss
  src/components/link-control/editor.scss
  src/components/maxi-block/maxiBlock.js
  src/components/toolbar/components/text-link/editor.scss
  src/css/style.scss
  src/extensions/dom/dom.js
  src/extensions/dom/isPostEditor.js
Labels: size:XXL

#5729 Issue 5470 - Add dropdown to select where in block link should be
  e2e-tests/components/toolbar/components/link/index.spec.js
  src/blocks/button-maxi/data.js
  src/components/button/index.js
  src/components/toolbar/components/link/index.js
  src/css/style.scss
  src/extensions/save/index.js
Labels: 🌟 enhancement, Final code review, lgtm, size:M

#5808 Issue 5805: default block
  e2e-tests/components/block-resizer/index.spec.js
  e2e-tests/components/icon/index.spec.js
  e2e-tests/components/toolbar/components/delete/index.spec.js
  src/components/block-inserter/editor.scss
  src/components/maxi-block/maxiBlock.js
  src/css/editor.scss
  src/extensions/dom/dom.js
  src/extensions/maxi-block/withMaxiProps.js
Labels: 🙏 high priority, Final code review, from support, lgtm, size:L, 2.0.4

#5810 2.0.4
  changelog.txt
  e2e-tests/blocks/Divider-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/Group-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/button-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/column-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/container-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/number-counter-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/row-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/svg-icon-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/text-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/video-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/components/background/__snapshots__/SVGIconBackground.spec.js.snap
  e2e-tests/components/icon-control/__snapshots__/index.spec.js.snap
  e2e-tests/components/repeater/__snapshots__/index.spec.js.snap
  e2e-tests/components/repeater/content.js
  e2e-tests/components/svg-color/__snapshots__/index.spec.js.snap
  e2e-tests/components/svg-stroke-width-control/__snapshots__/index.spec.js.snap
  e2e-tests/components/video-options-control/__snapshots__/index.spec.js.snap
  languages/maxi-blocks.pot
  plugin.php
  readme.txt
  src/components/maxi-block/maxiBlock.js
  src/css/editor.scss
Labels: size:M

#5804 Issue 5775 - Add rem units to typography control
  src/components/advanced-number-control/index.js
  src/components/typography-control/index.js
  src/css/editor.scss
Labels: 🌟 enhancement, Final code review, lgtm, size:M
