Repository maxi-blocks/maxi-blocks, pull requests merged in 2025-01, with the labels that each got.

#5838 Issue 4227 - used `withRTC` HOC instead of manually using `ResponsiveTabsControl`
  e2e-tests/components/color-control/index.spec.js
  e2e-tests/components/repeater/index.spec.js
  src/components/background-control/backgroundLayersControl.js
  src/components/background-control/colorLayer.js
  src/components/background-control/utils.js
  src/components/toolbar/components/background-color/background-color.js
  src/components/toolbar/components/background-color/block-background-color.js
Labels: bug 🐛, Final code review, lgtm, size:L

#5839 Issues 4343, 3699 - fixed the helper errors
  .github/workflows/e2e-test.yml
  .github/workflows/unit-test.yml
  src/extensions/styles/helpers/getBackgroundStyles.js
  src/extensions/styles/helpers/getMarginPaddingStyles.js
  src/extensions/styles/helpers/getPositionStyles.js
  src/extensions/styles/helpers/getSVGStyles.js
  src/extensions/styles/helpers/getSizeStyles.js
  src/extensions/styles/helpers/test/__snapshots__/getBackgroundStyles.js.snap
  src/extensions/styles/helpers/test/__snapshots__/getSizeStyles.js.snap
  src/extensions/styles/helpers/test/getBackgroundStyles.js
  src/extensions/styles/helpers/test/getSizeStyles.js
  src/extensions/styles/utils.js
Labels: bug 🐛, Final code review, lgtm, size:M

#5849 Issue 5676: fix sidebar scroll for IB transform
  src/css/editor.scss
Labels: bug 🐛, Final code review, lgtm, size:XS

#5848 Issue 5823: pagination when CL is disabled
  src/components/maxi-block/innerBlocksBlock.js
Labels: Final code review, lgtm, size:XS

#5847 Issue 5785: double click
  src/editor/library/container.js
Labels: bug 🐛, Final code review, lgtm, size:XS

#5853 Issue 5852: Fix re-render for SC modal
  src/editor/style-cards/maxiStyleCardsEditor.js
Labels: bug 🐛, Final code review, lgtm, size:M

#5831 Issue 5825 - Add "Keep only text content" switch
  core/class-maxi-dynamic-content.php
  src/components/dynamic-content/index.js
  src/extensions/styles/defaults/dynamicContent.js
Labels: 🌟 enhancement, Final code review, lgtm, size:L

#5850 Issue 5602: Fix toolbar
  src/editor/responsive-selector/editor.scss
Labels: bug 🐛, Final code review, size:XS

#5854 Issue 4441: Fix wp filesystem for a multisite with sub-domains
  core/admin/class-maxi-dashboard.php
  core/blocks/class-maxi-block.php
  core/blocks/utils/get_block_attributes.php
  core/blocks/utils/get_default_attribute.php
  core/blocks/utils/get_group_attributes.php
  core/class-maxi-image-crop.php
  core/class-maxi-local-fonts.php
  core/class-maxi-style-cards.php
  core/class-maxi-styles.php
Labels: bug 🐛, Final code review, size:L

#5858 Add back author dc / cl options
  core/class-maxi-dynamic-content.php
  src/extensions/DC/constants.js
  src/extensions/DC/getDCEntity.js
Labels: 🌟 enhancement, Final code review, lgtm, size:S

#5863 Fix failing fonts test
  e2e-tests/components/font-family-selector/index.spec.js
Labels: bug 🐛, front testing, lgtm, size:XS

#5861 Issue 5860: Fix 'auto' value
  e2e-tests/components/font-family-selector/index.spec.js
  src/extensions/styles/helpers/getBackgroundStyles.js
  src/extensions/styles/helpers/getMarginPaddingStyles.js
  src/extensions/styles/helpers/getPositionStyles.js
Labels: bug 🐛, Final code review, lgtm, size:S

#5859 Issue 5688 dc
  src/components/context-loop/index.js
  src/components/dynamic-content/index.js
  src/editor/library/utils/onRequestInsertPattern.js
  src/extensions/DC/constants.js
  src/extensions/DC/getDCOptions.js
  src/extensions/DC/validateDCAttributes.js
  src/extensions/DC/withMaxiContextLoop.js
Labels: Final code review, lgtm, size:L

#5865 Fix xxl breakpoint styles
  src/extensions/maxi-block/maxiBlockComponent.js
  src/extensions/relations/updateRelationsRemotely.js
Labels: Final code review, lgtm, size:XS

#5842 Issue 4517 - Fix and enhance e2e DC tests
  .vscode/launch.json
  e2e-tests/components/dynamic-content/author.spec.js
  e2e-tests/components/dynamic-content/category.spec.js
  e2e-tests/components/dynamic-content/component.spec.js
  e2e-tests/components/dynamic-content/content.js
  e2e-tests/components/dynamic-content/media.spec.js
  e2e-tests/components/dynamic-content/page.spec.js
  e2e-tests/components/dynamic-content/post.spec.js
  e2e-tests/components/dynamic-content/site.spec.js
  e2e-tests/components/toolbar/components/link/__snapshots__/index.spec.js.snap
  e2e-tests/components/toolbar/components/link/index.spec.js
  e2e-tests/utils/addImageToImageMaxi.js
  e2e-tests/utils/addImageToLibrary.js
  src/components/dynamic-content/index.js
  src/extensions/DC/getDCLink.js
  src/extensions/DC/getDCOptions.js
Labels: lgtm, size:XL

#5870 Issue 4888: styles and js on a page without maxi
  core/class-maxi-blocks.php
  core/class-maxi-style-cards.php
  core/class-maxi-styles.php
Labels: bug 🐛, optimization, Final code review, lgtm, size:L, 2.0.7
