Repository maxi-blocks/maxi-blocks, pull requests merged in 2025-05, with the labels that each got.

#5936 Fix menu link hover in sc
  src/extensions/maxi-block/cleanAttributes.js
Labels: Final code review, size:XS, 2.1.1

#5934 Issue 5919: ctrl+b
  src/extensions/text/formats/flatFormatsWithClass.js
  src/extensions/text/formats/test/flatFormatsWithClass.js
  src/extensions/text/formats/test/setFormatWithClass.js
Labels: Final code review, lgtm, size:S, 2.1.1

#5933 Patterns placeholder image
  core/admin/class-maxi-dashboard.php
  core/class-maxi-api.php
  src/editor/library/container.js
  src/editor/library/utils/imageUploader.js
  src/extensions/store/actions.js
  src/extensions/store/controls.js
  src/extensions/store/reducer.js
Labels: Final code review, lgtm, size:L, 2.1.1

#5945 Revert block delete combination for WP 6.8.1
  src/components/toolbar/components/delete/index.js
  src/components/toolbar/components/more-settings/editor.scss
Labels: 👩‍💻 pre-code testing, Final code review, lgtm, size:XS, 2.1.1

#5944 Issue 5937: php 8.4
  core/blocks/style-helpers/get_background_styles.php
  core/blocks/style-helpers/get_transform_styles.php
  core/blocks/utils/get_attributes_value.php
  core/blocks/utils/get_default_attribute.php
  core/class-maxi-local-fonts.php
  core/class-maxi-styles.php
Labels: bug 🐛, Final code review, from support, lgtm, size:M, 2.1.1

#5929 Issue 5928: Show all categories, tags, custom taxonomies in the CL/DC dropdowns
  src/components/context-loop/index.js
  src/components/dynamic-content/index.js
  src/extensions/DC/getDCOptions.js
  src/extensions/DC/validateDCAttributes.js
  src/extensions/DC/withMaxiContextLoop.js
Labels: 🌟 enhancement, Final code review, ⛏ ++ needs deep testing ++ ⛏, lgtm, size:L, 2.1.1

#5950 Add tests for relations and DC
  jest/jest-unit-global.setup.js
  jest/jest-unit.config.js
  jest/jest-unit.setup.js
  src/components/context-loop/index.js
  src/components/dynamic-content/index.js
  src/extensions/DC/constants.js
  src/extensions/DC/getDCContent.js
  src/extensions/DC/getDCLink.js
  src/extensions/DC/getDCMedia.js
  src/extensions/DC/getDCValues.js
  src/extensions/DC/getTypes.js
  src/extensions/DC/getWCContent.js
  src/extensions/DC/store/actions.js
  src/extensions/DC/store/controls.js
  src/extensions/DC/store/index.js
  src/extensions/DC/store/initConstants.js
  src/extensions/DC/store/reducer.js
  src/extensions/DC/store/resolvers.js
  src/extensions/DC/store/selectors.js
  src/extensions/DC/store/test/actions.js
  src/extensions/DC/store/test/controls.js
  src/extensions/DC/store/test/reducer.js
  src/extensions/DC/test/__snapshots__/getDCOptions.js.snap
  src/extensions/DC/test/fetchAndUpdateDCData.js
  src/extensions/DC/test/getCLAttributes.js
  src/extensions/DC/test/getDCContent.js
  src/extensions/DC/test/getDCEntity.js
  src/extensions/DC/test/getDCImgSVG.js
  src/extensions/DC/test/getDCLink.js
  src/extensions/DC/test/getDCMedia.js
  src/extensions/DC/test/getDCNewLinkSettings.js
  src/extensions/DC/test/getDCOptions.js
  src/extensions/DC/test/getDCValues.js
  src/extensions/DC/test/getTypes.js
  src/extensions/DC/test/getWCContent.js
  src/extensions/DC/test/processDCDate.js
  src/extensions/DC/test/useMaxiDCLink.js
  src/extensions/DC/test/utils.js
  src/extensions/DC/test/validateDCAttributes.js
  src/extensions/DC/utils.js
  src/extensions/relations/store/test/actions.js
  src/extensions/relations/store/test/reducer.js
  src/extensions/relations/store/test/selectors.js
Labels: Final code review, lgtm, size:XXL

#5949 Issue 5948: sc
  e2e-tests/components/repeater/__snapshots__/index.spec.js.snap
  src/extensions/maxi-block/maxiBlockComponent.js
  src/extensions/style-cards/getSCStyles.js
  src/extensions/style-cards/test/__snapshots__/getSCStyles.js.snap
  src/extensions/styles/frontendStyleGenerator.js
  src/extensions/styles/migrators/blockMigrator.js
  src/extensions/styles/migrators/bottomGapMigrator.js
Labels: bug 🐛, Final code review, lgtm, size:L, 2.1.1

#5956 Fix fatal error on php 8.2
  core/class-maxi-styles.php
Labels: bug 🐛, Final code review, lgtm, size:XS

#5951 Issue 5379 - fix icon padding units
  e2e-tests/components/icon-control/__snapshots__/index.spec.js.snap
  e2e-tests/components/icon-control/index.spec.js
  e2e-tests/components/relation-control/__snapshots__/button-maxi.spec.js.snap
  src/components/icon-control/index.js
Labels: bug 🐛, Final code review, lgtm, size:M
