Repository maxi-blocks/maxi-blocks, pull requests merged in 2025-03, with the labels that each got.

#5894 Add missing unit tests 2
  src/components/custom-css-control/test/utils.js
  src/extensions/style-cards/store/reducer.js
  src/extensions/style-cards/store/resolvers.js
  src/extensions/style-cards/store/test/controls.js
  src/extensions/style-cards/store/test/reducer.js
  src/extensions/style-cards/store/test/resolvers.js
  src/extensions/style-cards/store/test/selectors.js
  src/extensions/styles/store/reducer.js
  src/extensions/styles/store/test/actions.js
  src/extensions/styles/store/test/controls.js
  src/extensions/styles/store/test/reducer.js
  src/extensions/styles/store/test/selectors.js
  src/extensions/styles/transitions/test/__snapshots__/createTransitionObj.js.snap
  src/extensions/styles/transitions/test/createIconTransitions.js
  src/extensions/styles/transitions/test/createTransitionObj.js
  src/extensions/styles/transitions/test/setTransitionToSelectors.js
  src/extensions/styles/transitions/test/transitionAttributesCreator.js
Labels: Final code review, lgtm, size:XXL

#5898 DC: Fix tags for single post individual template
  src/extensions/DC/getDCEntity.js
Labels: bug 🐛, 🙏 need for library, Final code review, lgtm, size:L, 2.0.9

#5899 Issue 5896: author dc links
  core/class-maxi-dynamic-content.php
  e2e-tests/blocks/Divider-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/Group-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/button-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/column-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/container-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/map-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/number-counter-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/row-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/svg-icon-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/text-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/video-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/components/background/__snapshots__/SVGIconBackground.spec.js.snap
  e2e-tests/components/dynamic-content/content.js
  e2e-tests/components/icon-control/__snapshots__/index.spec.js.snap
  e2e-tests/components/repeater/__snapshots__/index.spec.js.snap
  e2e-tests/components/repeater/content.js
  e2e-tests/components/svg-color/__snapshots__/index.spec.js.snap
  e2e-tests/components/svg-stroke-width-control/__snapshots__/index.spec.js.snap
  e2e-tests/components/video-options-control/__snapshots__/index.spec.js.snap
  js/maxi-email-obfuscate.js
  plugin.php
  readme.txt
  src/blocks/button-maxi/edit.js
  src/blocks/button-maxi/save.js
  src/blocks/text-maxi/edit.js
  src/blocks/text-maxi/save.js
  src/components/link-control/editor.scss
  src/components/toolbar/components/link/index.js
  src/components/toolbar/components/text-link/index.js
  src/extensions/DC/constants.js
  src/extensions/DC/getDCContent.js
  src/extensions/DC/getDCEntity.js
  src/extensions/DC/getDCLink.js
  src/extensions/DC/utils.js
  src/extensions/maxi-block/maxiBlockComponent.js
  src/extensions/styles/migrators/buttonAriaLabelMigrator.js
  src/extensions/styles/migrators/buttonIconTransitionMigrator.js
  src/extensions/styles/migrators/listItemMigrator.js
Labels: 🌟 enhancement, 🙏 need for library, Final code review, dynamic content, lgtm, size:L, 2.0.9

#5906 Issue 5905: Fix blockStyle missing on dragging a block
  src/components/toolbar/components/mover/index.js
Labels: bug 🐛, Final code review, lgtm, size:S, 2.0.9

#5909 Issue 5897: Fix copy - paste and detach synced block
  src/extensions/maxi-block/maxiBlockComponent.js
Labels: bug 🐛, Final code review, from support, lgtm, size:XS, 2.0.9

#5907 Missing unit tests 3
  src/extensions/fse/getTemplateViewIframe.js
  src/extensions/fse/test/getTemplatePart.js
  src/extensions/fse/test/getTemplatePartSlug.js
  src/extensions/fse/test/getTemplatePartTagName.js
  src/extensions/fse/test/getTemplatePartsIds.js
  src/extensions/fse/test/getTemplateViewIframe.js
  src/extensions/text/fonts/fontCacheUtils.js
  src/extensions/text/fonts/loadFontUtils.js
  src/extensions/text/fonts/loadFonts.js
  src/extensions/text/fonts/test/fontCacheUtils.js
  src/extensions/text/fonts/test/loadFonts.js
  src/extensions/text/fonts/test/loadFontsUtils.js
  src/extensions/text/fonts/test/utils.js
Labels: lgtm, size:XXL

#5913 Fix scrolling migrator
  src/extensions/styles/migrators/scrollEffectsMigrator.js
Labels: bug 🐛, 🙏 need for library, Final code review, lgtm, size:XS, 2.0.9

#5912 Issue 5910: Fix link hover not overwriting the palette colour
  src/extensions/maxi-block/cleanAttributes.js
Labels: bug 🐛, Final code review, lgtm, size:XS, 2.0.9

#5911 Issue 5869: small fixes
  src/blocks/button-maxi/inspector.js
  src/components/advanced-number-control/index.js
  src/components/inspector-tabs/inspector-typography.js
  src/components/typography-control/index.js
  src/editor/style-cards/maxiStyleCardsEditor.js
  src/extensions/maxi-block/cleanAttributes.js
Labels: Final code review, lgtm, size:L, 2.0.9
