Repository maxi-blocks/maxi-blocks, pull requests merged in 2025-07, with the labels that each got.

#5995 Fix wrong breakpoint styles on reusable block edit view
  src/extensions/maxi-block/maxiBlockComponent.js
Labels: bug 🐛, Final code review, lgtm, size:M

#6001 New authentication middleware
  .gitignore
  core/admin/admin.js
  core/admin/admin.scss
  core/admin/class-maxi-dashboard.php
  core/admin/maxi-allowed-html-tags.php
  core/admin/quick-start/class-maxi-quick-start.php
  core/admin/quick-start/css/quick-start.css
  core/admin/quick-start/js/quick-start.js
  core/admin/starter-sites/.eslintrc.json
  core/admin/starter-sites/package-lock.json
  core/admin/starter-sites/src/Main.js
  core/admin/starter-sites/src/auth/index.js
  core/admin/starter-sites/src/components/text-control/index.js
  core/admin/starter-sites/src/library/index.js
  core/admin/starter-sites/src/library/style.scss
  core/admin/starter-sites/src/library/toolbar.js
  core/admin/status-report/styles.css
  core/class-maxi-blocks.php
  e2e-tests/utils/openPreviewPage.js
  src/editor/auth/index.js
  src/editor/library/editor.scss
  src/editor/library/hooks.js
  src/editor/library/index.js
  src/editor/library/modal.js
  src/editor/library/toolbar.js
Labels: 🌟 enhancement, 🙏 high priority, 💪 hard, 🙏 need for library, Final code review, ⛏ ++ needs deep testing ++ ⛏, 🌈🌈 next major update 🌈🌈, lgtm, size:XXL, 2.1.3

#6005 Issue 5997: reusables editor maxi button
  src/editor/toolbar-buttons/index.js
Labels: 🌟 enhancement, Final code review, size:M, 2.1.4
