Repository maxi-blocks/maxi-blocks, pull requests merged in 2025-02, with the labels that each got.

#5866 General optimization
  core/admin/class-maxi-dashboard.php
  core/class-maxi-api.php
  core/class-maxi-blocks.php
  core/class-maxi-dynamic-content.php
  core/class-maxi-local-fonts.php
  e2e-tests/components/video-icon-control/index.spec.js
  e2e-tests/utils/addResponsiveTest.js
  src/extensions/maxi-block/maxiBlockComponent.js
  src/extensions/maxi-block/withMaxiLoader.js
  src/extensions/store/actions.js
  src/extensions/store/reducer.js
  src/extensions/styles/migrators/opacityTransitionMigrator.js
  src/extensions/text/fonts/fontCacheUtils.js
  src/extensions/text/fonts/loadFonts.js
  src/extensions/text/store/resolvers.js
Labels: optimization, front testing, Final code review, ⛏ ++ needs deep testing ++ ⛏, lgtm, size:XXL

#5873 Issue 5871: template parts editor width
  src/editor/responsive-selector/index.js
  src/extensions/dom/dom.js
  src/extensions/store/actions.js
Labels: Final code review, lgtm, size:L, fse, 2.0.7

#5875 Issue 5874: new AI models for Maxi
  core/admin/admin.js
  core/admin/class-maxi-dashboard.php
  package-lock.json
  package.json
  src/components/prompt-control/components/result-card/index.js
  src/components/prompt-control/index.js
  src/components/prompt-control/tabs/generate-tab/editor.scss
  src/components/prompt-control/tabs/generate-tab/index.js
  src/components/prompt-control/utils.js
Labels: Final code review, from support, lgtm, size:L, 2.0.7, AI

#5876 Add import alias auto replace
  .eslintrc.json
  package-lock.json
  package.json
Labels: 🌟 enhancement, lgtm, size:S

#5878 2.0.7
  changelog.txt
  e2e-tests/blocks/Divider-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/Group-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/button-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/column-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/container-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/number-counter-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/row-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/svg-icon-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/text-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/video-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/components/background/__snapshots__/SVGIconBackground.spec.js.snap
  e2e-tests/components/dynamic-content/content.js
  e2e-tests/components/icon-control/__snapshots__/index.spec.js.snap
  e2e-tests/components/repeater/__snapshots__/index.spec.js.snap
  e2e-tests/components/repeater/content.js
  e2e-tests/components/svg-color/__snapshots__/index.spec.js.snap
  e2e-tests/components/svg-stroke-width-control/__snapshots__/index.spec.js.snap
  e2e-tests/components/video-options-control/__snapshots__/index.spec.js.snap
  languages/maxi-blocks.pot
  plugin.php
  readme.txt
  src/editor/responsive-selector/index.js
  src/extensions/maxi-block/maxiBlockComponent.js
Labels: lgtm, size:XXL

#5884 2.0.8
  changelog.txt
  e2e-tests/blocks/Divider-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/Group-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/button-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/column-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/container-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/number-counter-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/row-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/svg-icon-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/text-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/video-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/components/background/__snapshots__/SVGIconBackground.spec.js.snap
  e2e-tests/components/dynamic-content/content.js
  e2e-tests/components/icon-control/__snapshots__/index.spec.js.snap
  e2e-tests/components/repeater/__snapshots__/index.spec.js.snap
  e2e-tests/components/repeater/content.js
  e2e-tests/components/svg-color/__snapshots__/index.spec.js.snap
  e2e-tests/components/svg-stroke-width-control/__snapshots__/index.spec.js.snap
  e2e-tests/components/video-options-control/__snapshots__/index.spec.js.snap
  languages/maxi-blocks.pot
  plugin.php
  readme.txt
  src/extensions/styles/migrators/bottomGapMigrator.js
Labels: size:M

#5883 Fix bottom margin migrator
  src/extensions/styles/migrators/bottomGapMigrator.js
Labels: bug 🐛, 🙏 high priority, Final code review, lgtm, size:XS, 2.0.8

#5891 Remove staging workflow
  .github/workflows/update-staging-maximaster.yml
Labels: size:M
