Repository maxi-blocks/maxi-blocks, pull requests merged in 2025-04, with the labels that each got.

#5914 Issue 5869
  core/defaults/defaultSC.json
  e2e-tests/blocks/map-maxi/index.spec.js
  e2e-tests/editor/style-cards/__snapshots__/button.spec.js.snap
  e2e-tests/editor/style-cards/__snapshots__/headings.spec.js.snap
  e2e-tests/editor/style-cards/__snapshots__/paragraph.spec.js.snap
  e2e-tests/setup-test-framework.js
  src/editor/library/container.js
  src/editor/style-cards/maxiStyleCardsEditor.js
  src/editor/style-cards/maxiStyleCardsTab.js
  src/extensions/maxi-block/cleanAttributes.js
  src/extensions/maxi-block/handleSetAttributes.js
  src/extensions/maxi-block/test/cleanAttributes.js
  src/extensions/style-cards/test/__snapshots__/getSCStyles.js.snap
  src/extensions/style-cards/test/__snapshots__/getSCVariablesObject.js.snap
  src/extensions/style-cards/test/__snapshots__/updateSCOnEditor.js.snap
Labels: bug 🐛, Final code review, size:L, 2.0.9

#5930 Issue 5927: divider
  e2e-tests/components/relation-control/__snapshots__/divider-maxi.spec.js.snap
  src/components/divider-control/index.js
  src/components/toolbar/components/divider-alignment/index.js
  src/components/toolbar/index.js
Labels: Final code review, lgtm, size:L, 2.1.0

#5925 Issue 5920: Remove link autocomplete
  src/components/link-control/index.js
Labels: Final code review, lgtm, size:S, 2.1.0

#5924 Fixes for WordPress 6.8
  changelog.txt
  e2e-tests/blocks/Divider-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/Group-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/button-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/column-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/container-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/map-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/number-counter-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/row-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/svg-icon-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/text-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/blocks/video-maxi/__snapshots__/index.spec.js.snap
  e2e-tests/components/background/__snapshots__/SVGIconBackground.spec.js.snap
  e2e-tests/components/dynamic-content/component.spec.js
  e2e-tests/components/dynamic-content/content.js
  e2e-tests/components/icon-control/__snapshots__/index.spec.js.snap
  e2e-tests/components/repeater/__snapshots__/index.spec.js.snap
  e2e-tests/components/repeater/content.js
  e2e-tests/components/svg-color/__snapshots__/index.spec.js.snap
  e2e-tests/components/svg-stroke-width-control/__snapshots__/index.spec.js.snap
  e2e-tests/components/video-options-control/__snapshots__/index.spec.js.snap
  e2e-tests/setup-test-framework.js
  languages/maxi-blocks.pot
  plugin.php
  readme.txt
  src/blocks/button-maxi/edit.js
  src/blocks/row-maxi/edit.js
  src/components/block-indicators/index.js
  src/components/block-resizer/index.js
  src/components/maxi-block/editor.scss
  src/components/toolbar/components/delete/index.js
  src/components/toolbar/components/more-settings/editor.scss
  src/css/editor.scss
  src/css/maxi-themes-banner.scss
  src/css/native-components.scss
  src/editor/toolbar-buttons/editor.scss
  src/extensions/dom/disableDragging.js
  src/extensions/dom/dom.js
  src/extensions/maxi-block/maxiBlockComponent.js
  src/extensions/maxi-block/withMaxiProps.js
  src/extensions/style-cards/getDefaultSCValue.js
  src/extensions/styles/getBlockStyle.js
  src/extensions/styles/test/getBlockStyle.js
Labels: bug 🐛, 🌈🌈 next major update 🌈🌈, size:L, 2.1.0

#5940 Add tests for relations folder
  src/extensions/relations/Relation.js
  src/extensions/relations/getIBStylesObj.js
  src/extensions/relations/test/Relation.js
  src/extensions/relations/test/getCleanResponseIBAttributes.js
  src/extensions/relations/test/getHoverStatus.js
  src/extensions/relations/test/getIBOptionsFromBlockData.js
  src/extensions/relations/test/getIBStylesObj.js
  src/extensions/relations/test/getRelatedAttributes.js
  src/extensions/relations/test/getTempAttributes.js
  src/extensions/relations/test/processRelations.js
  src/extensions/relations/test/updateRelationsRemotely.js
  src/extensions/relations/test/utils.js
Labels: Final code review, lgtm, size:XXL
